export interface StockData {
  BSE: string[];
  NSE: string[];
}

export const STOCK_DATA: Record<string, string[]> = {
  BSE: [
    "7Seas Entertainment Ltd", "A.F. Enterprises Ltd", "Aadhaar Ventures India Ltd",
    "Aar Shyam India Investment Company Ltd", "AARV Infratel Ltd", "ABC Gas International Ltd",
    "ABG Shipyard Ltd", "Abhinav Leasing & Finance Ltd", "Abhishek Corporation Ltd",
    "Abhishek Finlease Ltd", "Abhishek Infraventures Ltd", "Abirami Financial Services India Ltd",
    "Ace Men Engg Works Ltd", "Achal Investments Ltd", "ACIL Cotton Industries Ltd",
    "Acrow India Ltd", "Action Financial Services India Ltd", "Adarsh Mercantile Ltd",
    "Adarsh Plant Protect Ltd", "Adharshila Capital Services Ltd", "Adinath Textiles Ltd",
    "Aditri Industries Ltd", "Ador Multiproducts Ltd", "Advance Petrochemicals Ltd",
    "Advance PowerInfra Tech Ltd", "Advanced Micronic Devices Ltd", "Agio Paper & Industries Ltd",
    "Ajcon Global Services Ltd", "Ajwa Fun World & Resort Ltd", "Lesha Industries Ltd",
    "Alchemist Ltd", "Alfavision Overseas India Ltd", "Alka Diamond Industries Ltd",
    "Alka Securities Ltd", "Alps Industries Ltd", "Alps Motor Finance Ltd",
    "Amani Trading & Exports Ltd", "Amarnath Securities Ltd", "Amit Spinning Industries Ltd",
    "Amradeep Industries Ltd", "Aneri Fincap Ltd", "ANG Industries Ltd", "Anka India Ltd",
    "Ankit Metal & Power Ltd", "Anubhav Industrial Resources Ltd", "Apple Finance Ltd",
    "Apunka Invest Commercial Ltd", "Aravali Securities & Finance Ltd", "Arcuttipore Tea Company Ltd",
    "Ardi Investments & Trading Company Ltd", "Inland Printers Ltd", "Arman Holdings Ltd",
    "Artson Engineering Ltd", "Aruna Hotels Ltd", "Aryan Share and Stock Brokers Ltd",
    "Asahi Industries Ltd", "Ashiana Agro Industries Ltd", "Ashirwad Steels & Industries Ltd",
    "Ashutosh Paper Mills Ltd", "Asia Pack Ltd", "Asian Flora Ltd", "Asian Petroproducts & Exports Ltd",
    "Asis Logistics Ltd", "Aspira Pathlab & Diagnostics Ltd", "Atharv Enterprises Ltd",
    "Athena Global Technologies Ltd", "ATN International Ltd", "Autoriders Finance Ltd",
    "Aviva Industries Ltd", "Avon Lifesciences Ltd", "Ayoki Mercantile Ltd", "B. P. Capital Ltd",
    "B2B Software Technologies Ltd", "Bacil Pharma Ltd", "Bagadia Colourchem Ltd",
    "Bansisons Tea Industries Ltd", "Baroda Extrusion Ltd", "Baron Infotech Ltd",
    "Beeyu Overseas Ltd", "Best Eastern Hotels Ltd", "Bhagyashree Leasing & Finance Ltd",
    "Bhanot Construction & Housing Ltd", "Alan Scott Industries Ltd", "Bilpower Ltd",
    "Binny Mills Ltd", "Birdhi Chand Pannalal Agencies Ltd", "Birla Cotsyn (India) Ltd",
    "Bisil Plast Ltd", "Bits Ltd", "BKV Industries Ltd", "Bloom Dekor Ltd", "Bloom Industries Ltd",
    "Blue Chip India Ltd", "Blue Circle Services Ltd", "Blue Cloud Softech Solutions Ltd",
    "Blue Pearl Texspin Ltd", "Bluechip Stockspin Ltd", "BNR Udyog Ltd", "Bombay Potteries & Tiles Ltd",
    "Bonanza Industries Ltd", "Boston Leasing and Finance Ltd", "Boston Teknowsys (India) Ltd",
    "Brand Realty Services Ltd", "Bridge Securities Ltd", "Brijlaxmi Leasing & Finance Ltd",
    "BWL Ltd", "California Software Company Ltd", "Cals Refineries Ltd", "Canopy Finance Ltd",
    "Caprolactam Chemicals Ltd", "Centerac Technologies Ltd", "Central Provinces Railways Company Ltd",
    "Chamak Holdings Ltd", "Chandrima Mercantiles Ltd", "Charms Industries Ltd",
    "Chase Bright Steel Ltd", "Chennai Ferrous Industries Ltd", "Chitradurga Spintex Ltd",
    "CHPL Industries Ltd", "Cindrella Financial Services Ltd", "Cinerad Communications Ltd",
    "CISTRO Telelink Ltd", "Citi Port Financial Services Ltd", "Citizen Yarns Ltd", "Cityman Ltd",
    "Classic Filaments Ltd", "CNI Research Ltd", "Cochin Malabar Estates & Industries Ltd",
    "Combat Drugs Ltd", "Commex Technology Ltd", "Concrete Credit Ltd",
    "Consecutive Investment & Trading Company Ltd", "Continental Controls Ltd",
    "Continental Securities Ltd", "Corporate Merchant Bankers Ltd", "Cosboard Industries Ltd",
    "Coventry Coil-O-Matic Haryana Ltd", "Crazy Infotech Ltd", "Crescent Leasing Ltd",
    "Crestchem Ltd", "Cura Technologies Ltd", "Cyberscape Multimedia Ltd",
    "Dalmia Industrial Development Ltd", "Unimode Overseas Ltd", "Datasoft Application Software India Ltd",
    "Datiware Maritime Infra Ltd", "Dazzel Confindive Ltd", "DCM Financial Services Ltd",
    "Deccan Bearings Ltd", "Decillion Finance Ltd", "Decorous Investment & Trading Co Ltd",
    "Deepti Alloy Steel Ltd", "Delta Industrial Resources Ltd", "Delton Cables Ltd",
    "Woodsvilla Ltd", "Devhari Exports (India) Ltd", "Devine Impex Ltd", "Dharani Finance Ltd",
    "Dhruv Estates Ltd", "Dhruva Capital Services Ltd", "Dion Global Solutions Ltd",
    "Disha Resources Ltd", "Divinus Fabrics Ltd", "DMC Education Ltd", "DSJ Communications Ltd",
    "Dwitiya Trading Ltd", "e.com Infotech India Ltd", "East Buildtech Ltd", "Eastcoast Steel Ltd",
    "Eastern Silk Industries Ltd", "Ecoboard Industries Ltd", "Educomp Solutions Ltd",
    "Ejecta Marketing Ltd", "Ekam Leasing & Finance Company Ltd", "Elango Industries Ltd",
    "EMA India Ltd", "Emed.com Technologies Ltd", "Emerald Leisures Ltd", "Emmsons International Ltd",
    "Empee Sugars & Chemicals Ltd", "EPIC Energy Ltd", "Epsom Properties Ltd", "Escorts Finance Ltd",
    "Esha Media Research Ltd", "Eskay KnIT India Ltd", "Essar Securities Ltd", "Euro Asia Exports Ltd",
    "Euro Ceramics Ltd", "Euro Multivision Ltd", "Evergreen Textiles Ltd", "Everlon Synthetics Ltd",
    "Explicit Finance Ltd", "F Mec International Financial Services Ltd", "Facor Steels Ltd",
    "FGP Ltd", "Filmcity Media Ltd", "Fine Line Circuits Ltd", "Flora Corporation Ltd",
    "Flora Textiles Ltd", "Fortune International Ltd", "Fourth Generation Information Systems Ltd",
    "Fraser and Company Ltd", "Frontier Capital Ltd", "Frontier Informatics Ltd",
    "Fruition Venture Ltd", "Futuristic Securities Ltd", "ISL Consulting Ltd", "Gagan Gases Ltd",
    "Gajanan Securities Services Ltd", "Gajra Bevel Gears Ltd", "Galada Finance Ltd",
    "Galada Power & Telecommunication Ltd", "Galaxy Cloud Kitchens Ltd", "Ganesh Holdings Ltd",
    "Gangotri Iron & Steel Company Ltd", "Garg Furnace Ltd", "Garware Synthetics Ltd",
    "Gayatri BioOrganics Ltd", "Gayatri Tissue & Papers Ltd", "GDL Leasing & Finance Ltd",
    "Gemini Communication Ltd", "Danube Industries Ltd", "Genesis Ibrc India Ltd",
    "Genus Commu Trade Ltd", "Girdharilal Sugar & Allied Industries Ltd", "GK Consultants Ltd",
    "Global Land Masters Corporation Ltd", "Globe Commercials Ltd", "Globus Corpooration Ltd",
    "Gold Coin Health Foods Ltd", "Golden Capital Services Ltd", "Golden Carpets Ltd",
    "Gontermann Peipers India Ltd", "Gopal Iron & Steels Company Gujarat Ltd", "Govind Rubber Ltd",
    "Goyal Associates Ltd", "GR Cables Ltd", "G-Tech Info-Training Ltd", "GTN Textiles Ltd",
    "Gujarat Carbon & Industries Ltd", "Gujarat Foils Ltd", "Gujarat Lease Financing Ltd",
    "Gujarat Meditech Ltd", "Gujarat Toolroom Ltd", "Gujchem Distillers India Ltd",
    "Harmony Capital Service Ltd", "Hazoor Multi Projects Ltd", "HCKK Ventures Ltd",
    "HealthFore Technologies Ltd", "Heera Ispat Ltd", "Hemang Resources Ltd", "Hemo Organic Ltd",
    "High Street Filatex Ltd", "Hilton Metal Forging Ltd", "Himalaya Granites Ltd",
    "Himalchuli Food Products Ltd", "Hindustan Bio Sciences Ltd", "Hindustan Motors Ltd",
    "Hipolin Ltd", "Hit Kit Global Solutions Ltd", "Hotel Rugby Ltd", "HRB Floriculture Ltd",
    "Hypersoft Technologies Ltd", "IB Infotech Enterprises Ltd", "ICSA (India) Ltd",
    "IFL Promoters Ltd", "IGC Industries Ltd", "IITL Projects Ltd", "IKF Technologies Ltd",
    "IMC Finance Ltd", "Impex Ferro Tech Ltd", "Inceptum Enterprises Ltd", "Incon Engineers Ltd",
    "Indergiri Finance Ltd", "India Lease Development Ltd", "Indian Bright Steel Company Ltd",
    "Indo Asia Finance Ltd", "Indo Cotspin Ltd", "Indo Credit Capital Ltd", "Indo-Global Enterprises Ltd",
    "Indra Industries Ltd", "Indrayani Biotech Ltd", "Indsoya Ltd", "Indus Finance Ltd",
    "Inertia Steel Ltd", "Infomedia Press Ltd", "Infra Industries Ltd", "Infraquest International Ltd",
    "Infronics Systems Ltd", "Universal Credit & Securities Ltd", "Innocorp Ltd",
    "Innovation Software Exports Ltd", "Innoventive Venture Ltd", "Integra Capital Management Ltd",
    "Integra Garments And Textiles Ltd", "Integra Switchgear Ltd", "Integra Telecommunication & Software Ltd",
    "Integrated Capital Services Ltd", "Integrated Proteins Ltd", "Integrated Technologies Ltd",
    "Integrated Thermoplastics Ltd", "Intellivate Capital Advisors Ltd", "Intellivate Capital Ventures Ltd",
    "Interface Financial Services Ltd", "Interlink Petroleum Ltd", "International Data Management Ltd",
    "Invicta Meditek Ltd", "IO System Ltd", "I-Power Solutions India Ltd",
    "Ishaan Infrastructures and Shelters Ltd", "Ishwarshakti Holdings & Traders Ltd",
    "Generic Pharmasec Ltd", "iStreet Network Ltd", "Jagson Airlines Ltd", "Jaihind Projects Ltd",
    "Jaihind Synthetics Ltd", "Jain Marmo Industries Ltd", "Jay Energy & S Energies Ltd",
    "JCT Electronics Ltd", "JD Orgochem Ltd", "JIK Industries Ltd", "Jindal Capital Ltd",
    "JJ Exporters Ltd", "JRI Industries & Infrastructure Ltd", "JSL Industries Ltd",
    "Jupiter Industries & Leasing Ltd", "Justride Enterprises Ltd", "Jyoti Ltd", "Jyoti Overseas Ltd",
    "Jyoti Structures Ltd", "Jyotirgamya Enterprises Ltd", "K K Fincorp Ltd", "Kabra Drugs Ltd",
    "Kaiser Corporation Ltd", "Kakatiya Textiles Ltd", "Kamron Laboratories Ltd", "Kanel Industries Ltd",
    "Kapashi Commercial Ltd", "Kapil Cotex Ltd", "Kapil Raj Finance Ltd", "Karan Woo Sin Ltd",
    "Kartik Investments Trust Ltd", "Katare Spinning Mills Ltd", "Kausambi Vanijya Ltd",
    "Kavita Fabrics Ltd", "KCCL Plastic Ltd", "KGN Enterprises Ltd", "Khaitan Electricals Ltd",
    "Khatau Exim Ltd", "Khyati Multimedia Entertainment Ltd", "Kiduja India Ltd",
    "Kilburn Office Automation Ltd", "Kinetic Trust Ltd", "Kintech Renewables Ltd",
    "Kiran Print Pack Ltd", "Kiran Syntex Ltd", "K-Lifestyle & Industries Ltd", "KLK Electrical Ltd",
    "KMG Milk Food Ltd", "Koa Tools India Ltd", "Koffee Break Pictures Ltd",
    "Kohinoor Broadcasting Corporation Ltd", "Kore Foods Ltd", "Kreon Finnancial Services Ltd",
    "Kshitij Investments Ltd", "Kunststoffe Industries Ltd", "Kush Industries Ltd",
    "Lakhotia Polyesters (India) Ltd", "Laser Diamonds Ltd", "Layla Textile and Traders Ltd",
    "Ledo Tea Company Ltd", "Lee & Nee Softwares Exports Ltd", "Leena Consultancy Ltd",
    "Arihant Tournesol Ltd", "LGB Forge Ltd", "Linaks Microelectronics Ltd", "LN Industries India Ltd",
    "Lotus Chocolate Company Ltd", "Lynx Machinery & Commercials Ltd", "Macro International Exports Ltd",
    "Madhur Industries Ltd", "Mahalaxmi Seamless Ltd", "Mahasagar Travels Ltd", "Mahaveer Infoway Ltd",
    "Mahavir Industries Ltd", "Mangalya Soft Tech Ltd", "Manraj Housing Finance Ltd",
    "Manvijay Development Company Ltd", "Margo Finance Ltd", "Marsons Ltd", "Maruti Securities Ltd",
    "Master Chemicals Ltd", "Mather and Platt Fire Systems Ltd", "Mavi Industries Ltd",
    "Mayukh Dealtrade Ltd", "Bijoy Hans Ltd", "Mayur Leather Products Ltd", "MB Parikh Finstocks Ltd",
    "Medico Intercontinental Ltd", "Meenakshi Steel Industries Ltd", "Mefcom Agro Industries Ltd",
    "Mega Fin India Ltd", "Meglon Infra-Real (India) Ltd", "Mehta Housing Finance Ltd",
    "Mehta Securities Ltd", "Melstar Information Technologies Ltd", "Mena Mani Industries Ltd",
    "Mercury Metals Ltd", "Mercury Trade Links Ltd", "Mesco Pharmaceuticals Ltd",
    "Metkore Alloys & Industries Ltd", "Mewat Zinc Ltd", "MFL India Ltd", "MFS Intercorp Ltd",
    "Microse India Ltd", "Mid East Portfolio Management Ltd", "Mid India Industries Ltd",
    "Midwest Gold Ltd", "Milgrey Finance & Investments Ltd", "Millennium Online Solutions ( India ) Ltd",
    "Mini Diamonds India Ltd", "Mipco Seamless Rings Gujarat Ltd", "Mirch Technologies (India) Ltd",
    "Mobile Tele Communications Ltd", "Modern Dairies Ltd", "Modern Steels Ltd", "Modipon Ltd",
    "Monnet Industries Ltd", "Monotype India Ltd", "Moongipa Securities Ltd", "Morgan Ventures Ltd",
    "Mount Shivalik Industries Ltd", "MP Agro Industries Ltd", "MPIL Corporation Ltd",
    "Mpl Plastics Ltd", "Mrugesh Trading Ltd", "Mudunuru Ltd", "Mukat Pipes Ltd",
    "Multipurpose Trading & Agencies Ltd", "Munoth Capital Markets Ltd", "Munoth Communication Ltd",
    "Munoth Financial Services Ltd", "My Money Securities Ltd", "Nagarjuna Oil Refinery Ltd",
    "Nam Securities Ltd", "Narendra Investments (Delhi) Ltd", "Natura Hue Chem Ltd", "NB Footwear Ltd",
    "NCC Finance Ltd", "Neelkanth Rockminerals Ltd", "Negotium International Trade Ltd",
    "Neo Infracon Ltd", "Neogem India Ltd", "Netlink Solutions India Ltd", "Network Ltd",
    "Neueon Towers Ltd", "New Markets Advisory Ltd", "Springform Technology Ltd",
    "Nexus Commodities And Technologies Ltd", "Nicco Corporation Ltd", "Nicco Uco Alliance Credit Ltd",
    "Nidhi Granites Ltd", "Nimbus Foods Industries Ltd", "Nishtha Finance and Investment (India) Ltd",
    "Nitin Fire Protection Industries Ltd", "Nivi Trading Ltd", "Noble Polymers Ltd",
    "Noesis Industries Ltd", "Norris Medicines Ltd", "Northlink Fiscal and Capital Services Ltd",
    "Nouveau Global Ventures Ltd", "Nova Publications India Ltd", "NovaGold Petro Resources Ltd",
    "Nutricircle Ltd", "Nuway Organic Naturals India Ltd", "Oasis Tradelink Ltd",
    "Octal Credit Capital Ltd", "Omansh Enterprises Ltd", "Omega Ag-Seeds Punjab Ltd",
    "Omkar Overseas Ltd", "Omkar Pharmachem Ltd", "Omnitex Industries India Ltd",
    "Onesource Ideas Venture Ltd", "Ontic Finserve Ltd", "Oracle Credit Ltd", "Organic Coatings Ltd",
    "Orosil Smiths India Ltd", "Oscar Investments Ltd", "Deltron Ltd", "Oswal Overseas Ltd",
    "Oswal Yarns Ltd", "OTCO International Ltd", "Oxford Industries Ltd", "Ozone World Ltd",
    "Pact Industries Ltd", "Padam Cotton Yarns Ltd", "Palco Metals Ltd", "Palsoft Infosystems Ltd",
    "Pan Electronics India Ltd", "Panafic Industrials Ltd", "Pankaj Polymers Ltd",
    "Panyam Cements & Mineral Industries Ltd", "Paos Industries Ltd", "Parabolic Drugs Ltd",
    "Paras Petrofils Ltd", "Pariksha Fin- Invest- Lease Ltd", "Parker Agrochem Exports Ltd",
    "Parmax Pharma Ltd", "QGO Finance Ltd", "Parsharti Investment Ltd", "Parth Industries Ltd",
    "Pasupati Fincap Ltd", "Pawansut Holdings Ltd", "Pazel International Ltd",
    "Pennar Aluminium Company Ltd", "Petron Engineering Construction Ltd", "PH Capital Ltd",
    "PH Trading Ltd", "Pharmaids Pharmaceuticals Ltd", "Photoquip India Ltd", "Phyto Chem India Ltd",
    "Pincon Lifestyle Ltd", "Piramal Phytocare Ltd", "Pithampur Poly Products Ltd",
    "Planters Polysacks Ltd", "Polytex India Ltd", "Prabhav Industries Ltd", "Pradip Overseas Ltd",
    "Pratik Panels Ltd", "Gaekwar Mills Ltd", "Premier Ltd", "Prime Industries Ltd",
    "Prism Finance Ltd", "Prism Medico and Pharmacy Ltd", "Procal Electronics India Ltd",
    "Progressive Extractions & Exports Ltd", "Provogue (India) Ltd", "Mayur Floorings Ltd",
    "Punit Commercials Ltd", "Quantum Build-Tech Ltd", "Quasar India Ltd", "Quest Softech (India) Ltd",
    "Quintegra Solutions Ltd", "Raaj Medisafe India Ltd", "Raghunath International Ltd",
    "Rahul Merchandising Ltd", "Rainbow Foundations Ltd", "Rainbow Papers Ltd",
    "Raj Rayon Industries Ltd", "Rajasthan Gases Ltd", "Rajasthan Petro Synthetics Ltd",
    "Rajath Finance Ltd", "Rajeswari Infrastructure Ltd", "Rajkamal Synthetics Ltd",
    "Rajputana Investment and Finance Ltd", "Rajsanket Realty Ltd", "Rajvir Industries Ltd",
    "Ramsarup Industries Ltd", "Rander Corporation Ltd", "Rasoya Proteins Ltd",
    "Ratnamani Agro Industries Ltd", "Raymed Labs Ltd", "RB Gupta Financials Ltd", "RCC Cements Ltd",
    "Real News & Views Ltd", "Redex Protech Ltd", "Regal Entertainment & Consultants Ltd",
    "Regaliaa Realty Ltd", "Regency Trust Ltd", "Rekvina Laboratories Ltd", "Response Informatics Ltd",
    "Resurgere Mines & Minerals India Ltd", "Retro Green Revolution Ltd", "Richa Industries Ltd",
    "Richirich Inventures Ltd", "Riga Sugar Company Ltd", "Rishab Special Yarns Ltd",
    "Rohit Ferro-Tech Ltd", "Roselabs Finance Ltd", "Rotographics (India) Ltd", "Roxy Exports Ltd",
    "Royal Cushion Vinyl Products Ltd", "RSC International Ltd", "RT Exports Ltd",
    "Rubra Medicaments Ltd", "Ruchika Industries India Ltd", "S Kumars.Com Ltd", "S T Services Ltd",
    "SAB Events & Governance Now Media Ltd", "Sabrimala Industries India Ltd",
    "Sadbhav Infrastructure Project Ltd", "Safal Herbs Ltd", "Safal Securities Ltd",
    "Sagar Productions Ltd", "Oswal Leasing Ltd", "Prem Somani Financial Services Ltd",
    "Sagar Tourist Resorts Ltd", "Sai Industries Ltd", "Sai Moh Auto Links Ltd", "Samtel India Ltd",
    "Samtex Fashions Ltd", "Sanathnagar Enterprises Ltd", "Sang Froid Labs (India) Ltd",
    "Sangam Renewables Ltd", "Sanghi Corporate Services Ltd", "Sanjivani Paranteral Ltd",
    "Santosh Fine Fab Ltd", "Saptarishi Agro Industries Ltd", "Sarda Papers Ltd", "Sarda Proteins Ltd",
    "Savani Financials Ltd", "Savant Infocomm Ltd", "SC Agrotech Ltd", "Scandent Imaging Ltd",
    "Schablona India Ltd", "Scintilla Commercial & Credit Ltd", "Sea Gold Aqua Farms Ltd",
    "Sea TV Network Ltd", "Seasons Furnishings Ltd", "Secunderabad Healthcare Ltd",
    "Sellwin Traders Ltd", "Senbo Industries Ltd", "Senthil Infotek Ltd", "Servoteach Industries Ltd",
    "Sezal Glass Ltd", "SFL International Ltd", "Sai Capital Ltd", "Shaba Chemicals Ltd",
    "Shalimar Agencies Ltd", "Shantai Industries Ltd", "Sharanam Infraproject and Trading Ltd",
    "Sharp India Ltd", "Sharp Investments Ltd", "Shashank Traders Ltd", "Shekhawati Poly Yarn Ltd",
    "Sheshadri Industries Ltd", "Shah Construction Company Ltd", "Shilpi Cable Technologies Ltd",
    "Shiva Medicare Ltd", "Shivagrico Implements Ltd", "Shivamshree Businesses Ltd",
    "Shree Bhawani Paper Mills Ltd", "Shree Ganesh Biotech (India) Ltd", "Shree Ganesh Elastoplast Ltd",
    "Shree Ganesh Forgings Ltd", "Shree Manufacturing Company Ltd", "Shree Nidhi Trading Co. Ltd",
    "Shree Pacetronix Ltd", "Shree Salasar Investments Ltd", "Shreyas Intermediates Ltd",
    "Shri Niwas Leasing And Finance Ltd", "Shricon Industries Ltd",
    "Shriram Asset Management Company Ltd", "Shukra Bullions Ltd", "Shyam Telecom Ltd",
    "Shyama Infosys Ltd", "Shyamkamal Investments Ltd", "Siddha Ventures Ltd", "Sidh Automobiles Ltd",
    "Siel Financial Services Ltd", "Sikozy Realtors Ltd", "Silicon Valley Infotech Ltd",
    "Silver Oak India Ltd", "Silveroak Commercials Ltd", "Silverpoint Infratech Ltd",
    "Simplex Mills Company Ltd", "Simplex Papers Ltd", "Specular Marketing & Financing Ltd",
    "Sinnar Bidi Udyog Ltd", "SIP Industries Ltd", "Sir Shadi Lal Enterprises Ltd",
    "Sita Shree Food Products Ltd", "Skyline Ventures India Ltd", "SM Energy Teknik & Electronics Ltd",
    "Smiths & Founders (India) Ltd", "SMS Techsoft (India) Ltd", "Sobhagya Mercantile Ltd",
    "Sofcom Systems Ltd", "Softbpo Global Services Ltd", "Solid Carbide Tools Ltd",
    "Solis Marketing Ltd", "Soma Textiles & Industries Ltd", "Sonal Adhesives Ltd",
    "Soni Medicare Ltd", "Source Industries (India) Ltd", "South Asian Enterprises Ltd",
    "Southern Ispat and Energy Ltd", "Southern Latex Ltd", "Southern Online Bio Technologies Ltd",
    "Sowbhagya Media Ltd", "SP Capital Financing Ltd", "Sparc Systems Ltd",
    "Sparkling (India) Finshares Ltd", "Speciality Papers Ltd", "Spectra Industries Ltd",
    "Spectrum Foods Ltd", "Suvidha Infraestate Corporation Ltd", "Spentex Industries Ltd",
    "Spice Islands Apparels Ltd", "Spring Fields Infraventure Ltd", "Square Four Projects India Ltd",
    "SR Industries Ltd", "Cella Space Ltd", "Sreechem Resins Ltd",
    "Sri Lakshmi Saraswathi Textiles Arni Ltd", "Sri Ramakrishna Mills Coimbatore Ltd",
    "Sri Vajra Granites Ltd", "SRM Energy Ltd", "SS Organics Ltd",
    "Standard Shoe Sole and Mould (India) Ltd", "Starlit Power Systems Ltd",
    "Steel Strips Infrastructures Ltd", "Steelco Gujarat Ltd", "Stellant Securities (India) Ltd",
    "Sterling Guaranty & Finance Ltd", "Sterling Powergensys Ltd", "Subhash Silk Mills Ltd",
    "Sudal Industries Ltd", "Sujala Trading & Holdings Ltd", "Sujana Universal Industries Ltd",
    "Sumeru Industries Ltd", "Sun Source India Ltd", "Sunbright Stock Broking Ltd",
    "Sungold Capital Ltd", "Sunitee Chemicals Ltd", "Sunraj Diamond Exports Ltd",
    "Super Domestic Machines Ltd", "Superb Papers Ltd", "Superior Finlease Ltd",
    "Supra Pacific Management Consultancy Ltd", "Supra Trends Ltd", "Supremex Shine Steels Ltd",
    "Surana Corporation Ltd", "Suryachakra Power Corporation Ltd", "Suryakrupa Finance Ltd",
    "Suryo Foods & Industries Ltd", "Terraform Magnum Ltd", "SVA India Ltd", "Svarnim Trade Udyog Ltd",
    "Swagruha Infrastructure Ltd", "Swarna Securities Ltd", "Sword & Shield Pharma Ltd",
    "Syncom Healthcare Ltd", "T Spiritual World Ltd", "Tamilnadu Jai Bharath Mills Ltd",
    "Tara Jewels Ltd", "Tarai Foods Ltd", "TCI Industries Ltd", "Terraform Realstate Ltd",
    "Tivoli Construction Ltd", "Thakral Services India Ltd", "Thambbi Modern Spinning Mills Ltd",
    "Thirdwave Financial Intermediaries Ltd", "Thomas Scott (India) Ltd", "Tirupati Fincorp Ltd",
    "Tirupati Tyres Ltd", "Transoceanic Properties Ltd", "Total Exports Ltd", "Towa Sokki Ltd",
    "TPI India Ltd", "Trans Asia Corporation Ltd", "Trans Financial Resources Ltd",
    "Trans Freight Containers Ltd", "Transglobe Foods Ltd", "Twin Roses Trades & Agencies Ltd",
    "TRC Financial Services Ltd", "Tribhuvan Housing Ltd", "Tricom Fruit Products Ltd",
    "Trident Tools Ltd", "Trijal Industries Ltd", "Trimurthi Ltd", "Trishakti Electronics & Industries Ltd",
    "Triton Corp Ltd", "Triveni Enterprises Ltd", "Trombo Extractions Ltd", "TSL Industries Ltd",
    "Tulasee Bio Ethanol Ltd", "Tulip Star Hotels Ltd", "Tulsi Extrusions Ltd",
    "Modulex Construction Technologies Ltd", "Tuticorin Alkali Chemicals & Fertilisers Ltd",
    "Pulsar International Ltd", "Typhoon Financial Services Ltd", "Typhoon Holdings Ltd",
    "Sagar Systech Ltd", "United Textiles Ltd", "Unity Infraprojects Ltd", "Universal Arts Ltd",
    "Shikhar Leasing & Trading Ltd", "Uniworth Ltd", "USG Tech Solutions Ltd", "Ushdev International Ltd",
    "Usher Agro Ltd", "Vaishno Cement Company Ltd", "Vallabh Poly Plast International Ltd",
    "Vani Commercials Ltd", "Vantage Knowledge Academy Ltd", "Vardhaman Laboratories Ltd",
    "Vardhman Concrete Ltd", "Vardhman Polytex Ltd", "Vas Infrastructure Ltd",
    "Vax Housing Finance Corporation Ltd", "VCCL Ltd", "VCK Capital Market Services Ltd",
    "Venlon Enterprises Ltd", "Ventura Textiles Ltd", "Venus Universal Ltd", "Vertical Industries Ltd",
    "Viceroy Hotels Ltd", "Victory Paper & Boards India Ltd", "Vikalp Securities Ltd",
    "Vimal Oil & Foods Ltd", "Vinaditya Trading Company Ltd", "Vintage Securities Ltd",
    "Vintron Informatics Ltd", "Virgo Global Ltd", "Virtualsoft Systems Ltd", "Visco Trade Associates Ltd",
    "Vishvprabha Ventures Ltd", "Vision Cinemas Ltd", "Vistar Amar Ltd", "Visu International Ltd",
    "Vitan Agro Industries Ltd", "Vivanza Biosciences Ltd", "Voltaire Leasing & Finance Ltd",
    "VR Woodart Ltd", "VSF Projects Ltd", "W. S. Industries (India) Ltd",
    "Welcure Drugs & Pharmaceuticals Ltd", "Wellesley Corporation Ltd", "Welterman International Ltd",
    "Williamson Financial Services Ltd", "Winsome Diamonds and Jewellery Ltd",
    "Winy Commercial & Fiscal Services Ltd", "Wisec Global Ltd", "Women Networks Ltd",
    "Sindu Valley Technologies Ltd", "Worth Investment & Trading Co Ltd", "XL Energy Ltd",
    "Yantra Natural Resources Ltd", "Yarn Syndicate Ltd", "Sunedison Infrastructure Ltd",
    "Yuranus Infrastructure Ltd", "Yuvraaj Hygiene Products Ltd", "Zenith Birla (India) Ltd",
    "Zenith Capitals Ltd", "Zicom Electronic Security Systems Ltd", "Zylog Systems Ltd"
  ],
  NSE: [] // Add NSE names here later
};