export interface StockData {
  BSE: string[];
  NSE: string[];
}

export const STOCK_DATA: Record<string, string[]> = {
  BSE: [
    "7Seas Entertainment Ltd", "A.F. Enterprises Ltd", "Aadhaar Ventures India Ltd",
    "Aar Shyam India Investment Company Ltd", "AARV Infratel Ltd", "ABC Gas International Ltd",
    "ABG Shipyard Ltd", "Abhinav Leasing & Finance Ltd", "Abhishek Corporation Ltd",
    "Abhishek Finlease Ltd", "Abhishek Infraventures Ltd", "Abirami Financial Services India Ltd",
    "Ace Men Engg Works Ltd", "Achal Investments Ltd", "ACIL Cotton Industries Ltd",
    "Acrow India Ltd", "Action Financial Services India Ltd", "Adarsh Mercantile Ltd",
    "Adarsh Plant Protect Ltd", "Adharshila Capital Services Ltd", "Adinath Textiles Ltd",
    "Aditri Industries Ltd", "Ador Multiproducts Ltd", "Advance Petrochemicals Ltd",
    "Advance PowerInfra Tech Ltd", "Advanced Micronic Devices Ltd", "Agio Paper & Industries Ltd",
    "Ajcon Global Services Ltd", "Ajwa Fun World & Resort Ltd", "Lesha Industries Ltd",
    "Alchemist Ltd", "Alfavision Overseas India Ltd", "Alka Diamond Industries Ltd",
    "Alka Securities Ltd", "Alps Industries Ltd", "Alps Motor Finance Ltd",
    "Amani Trading & Exports Ltd", "Amarnath Securities Ltd", "Amit Spinning Industries Ltd",
    "Amradeep Industries Ltd", "Aneri Fincap Ltd", "ANG Industries Ltd", "Anka India Ltd",
    "Ankit Metal & Power Ltd", "Anubhav Industrial Resources Ltd", "Apple Finance Ltd",
    "Apunka Invest Commercial Ltd", "Aravali Securities & Finance Ltd", "Arcuttipore Tea Company Ltd",
    "Ardi Investments & Trading Company Ltd", "Inland Printers Ltd", "Arman Holdings Ltd",
    "Artson Engineering Ltd", "Aruna Hotels Ltd", "Aryan Share and Stock Brokers Ltd",
    "Asahi Industries Ltd", "Ashiana Agro Industries Ltd", "Ashirwad Steels & Industries Ltd",
    "Ashutosh Paper Mills Ltd", "Asia Pack Ltd", "Asian Flora Ltd", "Asian Petroproducts & Exports Ltd",
    "Asis Logistics Ltd", "Aspira Pathlab & Diagnostics Ltd", "Atharv Enterprises Ltd",
    "Athena Global Technologies Ltd", "ATN International Ltd", "Autoriders Finance Ltd",
    "Aviva Industries Ltd", "Avon Lifesciences Ltd", "Ayoki Mercantile Ltd", "B. P. Capital Ltd",
    "B2B Software Technologies Ltd", "Bacil Pharma Ltd", "Bagadia Colourchem Ltd",
    "Bansisons Tea Industries Ltd", "Baroda Extrusion Ltd", "Baron Infotech Ltd",
    "Beeyu Overseas Ltd", "Best Eastern Hotels Ltd", "Bhagyashree Leasing & Finance Ltd",
    "Bhanot Construction & Housing Ltd", "Alan Scott Industries Ltd", "Bilpower Ltd",
    "Binny Mills Ltd", "Birdhi Chand Pannalal Agencies Ltd", "Birla Cotsyn (India) Ltd",
    "Bisil Plast Ltd", "Bits Ltd", "BKV Industries Ltd", "Bloom Dekor Ltd", "Bloom Industries Ltd",
    "Blue Chip India Ltd", "Blue Circle Services Ltd", "Blue Cloud Softech Solutions Ltd",
    "Blue Pearl Texspin Ltd", "Bluechip Stockspin Ltd", "BNR Udyog Ltd", "Bombay Potteries & Tiles Ltd",
    "Bonanza Industries Ltd", "Boston Leasing and Finance Ltd", "Boston Teknowsys (India) Ltd",
    "Brand Realty Services Ltd", "Bridge Securities Ltd", "Brijlaxmi Leasing & Finance Ltd",
    "BWL Ltd", "California Software Company Ltd", "Cals Refineries Ltd", "Canopy Finance Ltd",
    "Caprolactam Chemicals Ltd", "Centerac Technologies Ltd", "Central Provinces Railways Company Ltd",
    "Chamak Holdings Ltd", "Chandrima Mercantiles Ltd", "Charms Industries Ltd",
    "Chase Bright Steel Ltd", "Chennai Ferrous Industries Ltd", "Chitradurga Spintex Ltd",
    "CHPL Industries Ltd", "Cindrella Financial Services Ltd", "Cinerad Communications Ltd",
    "CISTRO Telelink Ltd", "Citi Port Financial Services Ltd", "Citizen Yarns Ltd", "Cityman Ltd",
    "Classic Filaments Ltd", "CNI Research Ltd", "Cochin Malabar Estates & Industries Ltd",
    "Combat Drugs Ltd", "Commex Technology Ltd", "Concrete Credit Ltd",
    "Consecutive Investment & Trading Company Ltd", "Continental Controls Ltd",
    "Continental Securities Ltd", "Corporate Merchant Bankers Ltd", "Cosboard Industries Ltd",
    "Coventry Coil-O-Matic Haryana Ltd", "Crazy Infotech Ltd", "Crescent Leasing Ltd",
    "Crestchem Ltd", "Cura Technologies Ltd", "Cyberscape Multimedia Ltd",
    "Dalmia Industrial Development Ltd", "Unimode Overseas Ltd", "Datasoft Application Software India Ltd",
    "Datiware Maritime Infra Ltd", "Dazzel Confindive Ltd", "DCM Financial Services Ltd",
    "Deccan Bearings Ltd", "Decillion Finance Ltd", "Decorous Investment & Trading Co Ltd",
    "Deepti Alloy Steel Ltd", "Delta Industrial Resources Ltd", "Delton Cables Ltd",
    "Woodsvilla Ltd", "Devhari Exports (India) Ltd", "Devine Impex Ltd", "Dharani Finance Ltd",
    "Dhruv Estates Ltd", "Dhruva Capital Services Ltd", "Dion Global Solutions Ltd",
    "Disha Resources Ltd", "Divinus Fabrics Ltd", "DMC Education Ltd", "DSJ Communications Ltd",
    "Dwitiya Trading Ltd", "e.com Infotech India Ltd", "East Buildtech Ltd", "Eastcoast Steel Ltd",
    "Eastern Silk Industries Ltd", "Ecoboard Industries Ltd", "Educomp Solutions Ltd",
    "Ejecta Marketing Ltd", "Ekam Leasing & Finance Company Ltd", "Elango Industries Ltd",
    "EMA India Ltd", "Emed.com Technologies Ltd", "Emerald Leisures Ltd", "Emmsons International Ltd",
    "Empee Sugars & Chemicals Ltd", "EPIC Energy Ltd", "Epsom Properties Ltd", "Escorts Finance Ltd",
    "Esha Media Research Ltd", "Eskay KnIT India Ltd", "Essar Securities Ltd", "Euro Asia Exports Ltd",
    "Euro Ceramics Ltd", "Euro Multivision Ltd", "Evergreen Textiles Ltd", "Everlon Synthetics Ltd",
    "Explicit Finance Ltd", "F Mec International Financial Services Ltd", "Facor Steels Ltd",
    "FGP Ltd", "Filmcity Media Ltd", "Fine Line Circuits Ltd", "Flora Corporation Ltd",
    "Flora Textiles Ltd", "Fortune International Ltd", "Fourth Generation Information Systems Ltd",
    "Fraser and Company Ltd", "Frontier Capital Ltd", "Frontier Informatics Ltd",
    "Fruition Venture Ltd", "Futuristic Securities Ltd", "ISL Consulting Ltd", "Gagan Gases Ltd",
    "Gajanan Securities Services Ltd", "Gajra Bevel Gears Ltd", "Galada Finance Ltd",
    "Galada Power & Telecommunication Ltd", "Galaxy Cloud Kitchens Ltd", "Ganesh Holdings Ltd",
    "Gangotri Iron & Steel Company Ltd", "Garg Furnace Ltd", "Garware Synthetics Ltd",
    "Gayatri BioOrganics Ltd", "Gayatri Tissue & Papers Ltd", "GDL Leasing & Finance Ltd",
    "Gemini Communication Ltd", "Danube Industries Ltd", "Genesis Ibrc India Ltd",
    "Genus Commu Trade Ltd", "Girdharilal Sugar & Allied Industries Ltd", "GK Consultants Ltd",
    "Global Land Masters Corporation Ltd", "Globe Commercials Ltd", "Globus Corpooration Ltd",
    "Gold Coin Health Foods Ltd", "Golden Capital Services Ltd", "Golden Carpets Ltd",
    "Gontermann Peipers India Ltd", "Gopal Iron & Steels Company Gujarat Ltd", "Govind Rubber Ltd",
    "Goyal Associates Ltd", "GR Cables Ltd", "G-Tech Info-Training Ltd", "GTN Textiles Ltd",
    "Gujarat Carbon & Industries Ltd", "Gujarat Foils Ltd", "Gujarat Lease Financing Ltd",
    "Gujarat Meditech Ltd", "Gujarat Toolroom Ltd", "Gujchem Distillers India Ltd",
    "Harmony Capital Service Ltd", "Hazoor Multi Projects Ltd", "HCKK Ventures Ltd",
    "HealthFore Technologies Ltd", "Heera Ispat Ltd", "Hemang Resources Ltd", "Hemo Organic Ltd",
    "High Street Filatex Ltd", "Hilton Metal Forging Ltd", "Himalaya Granites Ltd",
    "Himalchuli Food Products Ltd", "Hindustan Bio Sciences Ltd", "Hindustan Motors Ltd",
    "Hipolin Ltd", "Hit Kit Global Solutions Ltd", "Hotel Rugby Ltd", "HRB Floriculture Ltd",
    "Hypersoft Technologies Ltd", "IB Infotech Enterprises Ltd", "ICSA (India) Ltd",
    "IFL Promoters Ltd", "IGC Industries Ltd", "IITL Projects Ltd", "IKF Technologies Ltd",
    "IMC Finance Ltd", "Impex Ferro Tech Ltd", "Inceptum Enterprises Ltd", "Incon Engineers Ltd",
    "Indergiri Finance Ltd", "India Lease Development Ltd", "Indian Bright Steel Company Ltd",
    "Indo Asia Finance Ltd", "Indo Cotspin Ltd", "Indo Credit Capital Ltd", "Indo-Global Enterprises Ltd",
    "Indra Industries Ltd", "Indrayani Biotech Ltd", "Indsoya Ltd", "Indus Finance Ltd",
    "Inertia Steel Ltd", "Infomedia Press Ltd", "Infra Industries Ltd", "Infraquest International Ltd",
    "Infronics Systems Ltd", "Universal Credit & Securities Ltd", "Innocorp Ltd",
    "Innovation Software Exports Ltd", "Innoventive Venture Ltd", "Integra Capital Management Ltd",
    "Integra Garments And Textiles Ltd", "Integra Switchgear Ltd", "Integra Telecommunication & Software Ltd",
    "Integrated Capital Services Ltd", "Integrated Proteins Ltd", "Integrated Technologies Ltd",
    "Integrated Thermoplastics Ltd", "Intellivate Capital Advisors Ltd", "Intellivate Capital Ventures Ltd",
    "Interface Financial Services Ltd", "Interlink Petroleum Ltd", "International Data Management Ltd",
    "Invicta Meditek Ltd", "IO System Ltd", "I-Power Solutions India Ltd",
    "Ishaan Infrastructures and Shelters Ltd", "Ishwarshakti Holdings & Traders Ltd",
    "Generic Pharmasec Ltd", "iStreet Network Ltd", "Jagson Airlines Ltd", "Jaihind Projects Ltd",
    "Jaihind Synthetics Ltd", "Jain Marmo Industries Ltd", "Jay Energy & S Energies Ltd",
    "JCT Electronics Ltd", "JD Orgochem Ltd", "JIK Industries Ltd", "Jindal Capital Ltd",
    "JJ Exporters Ltd", "JRI Industries & Infrastructure Ltd", "JSL Industries Ltd",
    "Jupiter Industries & Leasing Ltd", "Justride Enterprises Ltd", "Jyoti Ltd", "Jyoti Overseas Ltd",
    "Jyoti Structures Ltd", "Jyotirgamya Enterprises Ltd", "K K Fincorp Ltd", "Kabra Drugs Ltd",
    "Kaiser Corporation Ltd", "Kakatiya Textiles Ltd", "Kamron Laboratories Ltd", "Kanel Industries Ltd",
    "Kapashi Commercial Ltd", "Kapil Cotex Ltd", "Kapil Raj Finance Ltd", "Karan Woo Sin Ltd",
    "Kartik Investments Trust Ltd", "Katare Spinning Mills Ltd", "Kausambi Vanijya Ltd",
    "Kavita Fabrics Ltd", "KCCL Plastic Ltd", "KGN Enterprises Ltd", "Khaitan Electricals Ltd",
    "Khatau Exim Ltd", "Khyati Multimedia Entertainment Ltd", "Kiduja India Ltd",
    "Kilburn Office Automation Ltd", "Kinetic Trust Ltd", "Kintech Renewables Ltd",
    "Kiran Print Pack Ltd", "Kiran Syntex Ltd", "K-Lifestyle & Industries Ltd", "KLK Electrical Ltd",
    "KMG Milk Food Ltd", "Koa Tools India Ltd", "Koffee Break Pictures Ltd",
    "Kohinoor Broadcasting Corporation Ltd", "Kore Foods Ltd", "Kreon Finnancial Services Ltd",
    "Kshitij Investments Ltd", "Kunststoffe Industries Ltd", "Kush Industries Ltd",
    "Lakhotia Polyesters (India) Ltd", "Laser Diamonds Ltd", "Layla Textile and Traders Ltd",
    "Ledo Tea Company Ltd", "Lee & Nee Softwares Exports Ltd", "Leena Consultancy Ltd",
    "Arihant Tournesol Ltd", "LGB Forge Ltd", "Linaks Microelectronics Ltd", "LN Industries India Ltd",
    "Lotus Chocolate Company Ltd", "Lynx Machinery & Commercials Ltd", "Macro International Exports Ltd",
    "Madhur Industries Ltd", "Mahalaxmi Seamless Ltd", "Mahasagar Travels Ltd", "Mahaveer Infoway Ltd",
    "Mahavir Industries Ltd", "Mangalya Soft Tech Ltd", "Manraj Housing Finance Ltd",
    "Manvijay Development Company Ltd", "Margo Finance Ltd", "Marsons Ltd", "Maruti Securities Ltd",
    "Master Chemicals Ltd", "Mather and Platt Fire Systems Ltd", "Mavi Industries Ltd",
    "Mayukh Dealtrade Ltd", "Bijoy Hans Ltd", "Mayur Leather Products Ltd", "MB Parikh Finstocks Ltd",
    "Medico Intercontinental Ltd", "Meenakshi Steel Industries Ltd", "Mefcom Agro Industries Ltd",
    "Mega Fin India Ltd", "Meglon Infra-Real (India) Ltd", "Mehta Housing Finance Ltd",
    "Mehta Securities Ltd", "Melstar Information Technologies Ltd", "Mena Mani Industries Ltd",
    "Mercury Metals Ltd", "Mercury Trade Links Ltd", "Mesco Pharmaceuticals Ltd",
    "Metkore Alloys & Industries Ltd", "Mewat Zinc Ltd", "MFL India Ltd", "MFS Intercorp Ltd",
    "Microse India Ltd", "Mid East Portfolio Management Ltd", "Mid India Industries Ltd",
    "Midwest Gold Ltd", "Milgrey Finance & Investments Ltd", "Millennium Online Solutions ( India ) Ltd",
    "Mini Diamonds India Ltd", "Mipco Seamless Rings Gujarat Ltd", "Mirch Technologies (India) Ltd",
    "Mobile Tele Communications Ltd", "Modern Dairies Ltd", "Modern Steels Ltd", "Modipon Ltd",
    "Monnet Industries Ltd", "Monotype India Ltd", "Moongipa Securities Ltd", "Morgan Ventures Ltd",
    "Mount Shivalik Industries Ltd", "MP Agro Industries Ltd", "MPIL Corporation Ltd",
    "Mpl Plastics Ltd", "Mrugesh Trading Ltd", "Mudunuru Ltd", "Mukat Pipes Ltd",
    "Multipurpose Trading & Agencies Ltd", "Munoth Capital Markets Ltd", "Munoth Communication Ltd",
    "Munoth Financial Services Ltd", "My Money Securities Ltd", "Nagarjuna Oil Refinery Ltd",
    "Nam Securities Ltd", "Narendra Investments (Delhi) Ltd", "Natura Hue Chem Ltd", "NB Footwear Ltd",
    "NCC Finance Ltd", "Neelkanth Rockminerals Ltd", "Negotium International Trade Ltd",
    "Neo Infracon Ltd", "Neogem India Ltd", "Netlink Solutions India Ltd", "Network Ltd",
    "Neueon Towers Ltd", "New Markets Advisory Ltd", "Springform Technology Ltd",
    "Nexus Commodities And Technologies Ltd", "Nicco Corporation Ltd", "Nicco Uco Alliance Credit Ltd",
    "Nidhi Granites Ltd", "Nimbus Foods Industries Ltd", "Nishtha Finance and Investment (India) Ltd",
    "Nitin Fire Protection Industries Ltd", "Nivi Trading Ltd", "Noble Polymers Ltd",
    "Noesis Industries Ltd", "Norris Medicines Ltd", "Northlink Fiscal and Capital Services Ltd",
    "Nouveau Global Ventures Ltd", "Nova Publications India Ltd", "NovaGold Petro Resources Ltd",
    "Nutricircle Ltd", "Nuway Organic Naturals India Ltd", "Oasis Tradelink Ltd",
    "Octal Credit Capital Ltd", "Omansh Enterprises Ltd", "Omega Ag-Seeds Punjab Ltd",
    "Omkar Overseas Ltd", "Omkar Pharmachem Ltd", "Omnitex Industries India Ltd",
    "Onesource Ideas Venture Ltd", "Ontic Finserve Ltd", "Oracle Credit Ltd", "Organic Coatings Ltd",
    "Orosil Smiths India Ltd", "Oscar Investments Ltd", "Deltron Ltd", "Oswal Overseas Ltd",
    "Oswal Yarns Ltd", "OTCO International Ltd", "Oxford Industries Ltd", "Ozone World Ltd",
    "Pact Industries Ltd", "Padam Cotton Yarns Ltd", "Palco Metals Ltd", "Palsoft Infosystems Ltd",
    "Pan Electronics India Ltd", "Panafic Industrials Ltd", "Pankaj Polymers Ltd",
    "Panyam Cements & Mineral Industries Ltd", "Paos Industries Ltd", "Parabolic Drugs Ltd",
    "Paras Petrofils Ltd", "Pariksha Fin- Invest- Lease Ltd", "Parker Agrochem Exports Ltd",
    "Parmax Pharma Ltd", "QGO Finance Ltd", "Parsharti Investment Ltd", "Parth Industries Ltd",
    "Pasupati Fincap Ltd", "Pawansut Holdings Ltd", "Pazel International Ltd",
    "Pennar Aluminium Company Ltd", "Petron Engineering Construction Ltd", "PH Capital Ltd",
    "PH Trading Ltd", "Pharmaids Pharmaceuticals Ltd", "Photoquip India Ltd", "Phyto Chem India Ltd",
    "Pincon Lifestyle Ltd", "Piramal Phytocare Ltd", "Pithampur Poly Products Ltd",
    "Planters Polysacks Ltd", "Polytex India Ltd", "Prabhav Industries Ltd", "Pradip Overseas Ltd",
    "Pratik Panels Ltd", "Gaekwar Mills Ltd", "Premier Ltd", "Prime Industries Ltd",
    "Prism Finance Ltd", "Prism Medico and Pharmacy Ltd", "Procal Electronics India Ltd",
    "Progressive Extractions & Exports Ltd", "Provogue (India) Ltd", "Mayur Floorings Ltd",
    "Punit Commercials Ltd", "Quantum Build-Tech Ltd", "Quasar India Ltd", "Quest Softech (India) Ltd",
    "Quintegra Solutions Ltd", "Raaj Medisafe India Ltd", "Raghunath International Ltd",
    "Rahul Merchandising Ltd", "Rainbow Foundations Ltd", "Rainbow Papers Ltd",
    "Raj Rayon Industries Ltd", "Rajasthan Gases Ltd", "Rajasthan Petro Synthetics Ltd",
    "Rajath Finance Ltd", "Rajeswari Infrastructure Ltd", "Rajkamal Synthetics Ltd",
    "Rajputana Investment and Finance Ltd", "Rajsanket Realty Ltd", "Rajvir Industries Ltd",
    "Ramsarup Industries Ltd", "Rander Corporation Ltd", "Rasoya Proteins Ltd",
    "Ratnamani Agro Industries Ltd", "Raymed Labs Ltd", "RB Gupta Financials Ltd", "RCC Cements Ltd",
    "Real News & Views Ltd", "Redex Protech Ltd", "Regal Entertainment & Consultants Ltd",
    "Regaliaa Realty Ltd", "Regency Trust Ltd", "Rekvina Laboratories Ltd", "Response Informatics Ltd",
    "Resurgere Mines & Minerals India Ltd", "Retro Green Revolution Ltd", "Richa Industries Ltd",
    "Richirich Inventures Ltd", "Riga Sugar Company Ltd", "Rishab Special Yarns Ltd",
    "Rohit Ferro-Tech Ltd", "Roselabs Finance Ltd", "Rotographics (India) Ltd", "Roxy Exports Ltd",
    "Royal Cushion Vinyl Products Ltd", "RSC International Ltd", "RT Exports Ltd",
    "Rubra Medicaments Ltd", "Ruchika Industries India Ltd", "S Kumars.Com Ltd", "S T Services Ltd",
    "SAB Events & Governance Now Media Ltd", "Sabrimala Industries India Ltd",
    "Sadbhav Infrastructure Project Ltd", "Safal Herbs Ltd", "Safal Securities Ltd",
    "Sagar Productions Ltd", "Oswal Leasing Ltd", "Prem Somani Financial Services Ltd",
    "Sagar Tourist Resorts Ltd", "Sai Industries Ltd", "Sai Moh Auto Links Ltd", "Samtel India Ltd",
    "Samtex Fashions Ltd", "Sanathnagar Enterprises Ltd", "Sang Froid Labs (India) Ltd",
    "Sangam Renewables Ltd", "Sanghi Corporate Services Ltd", "Sanjivani Paranteral Ltd",
    "Santosh Fine Fab Ltd", "Saptarishi Agro Industries Ltd", "Sarda Papers Ltd", "Sarda Proteins Ltd",
    "Savani Financials Ltd", "Savant Infocomm Ltd", "SC Agrotech Ltd", "Scandent Imaging Ltd",
    "Schablona India Ltd", "Scintilla Commercial & Credit Ltd", "Sea Gold Aqua Farms Ltd",
    "Sea TV Network Ltd", "Seasons Furnishings Ltd", "Secunderabad Healthcare Ltd",
    "Sellwin Traders Ltd", "Senbo Industries Ltd", "Senthil Infotek Ltd", "Servoteach Industries Ltd",
    "Sezal Glass Ltd", "SFL International Ltd", "Sai Capital Ltd", "Shaba Chemicals Ltd",
    "Shalimar Agencies Ltd", "Shantai Industries Ltd", "Sharanam Infraproject and Trading Ltd",
    "Sharp India Ltd", "Sharp Investments Ltd", "Shashank Traders Ltd", "Shekhawati Poly Yarn Ltd",
    "Sheshadri Industries Ltd", "Shah Construction Company Ltd", "Shilpi Cable Technologies Ltd",
    "Shiva Medicare Ltd", "Shivagrico Implements Ltd", "Shivamshree Businesses Ltd",
    "Shree Bhawani Paper Mills Ltd", "Shree Ganesh Biotech (India) Ltd", "Shree Ganesh Elastoplast Ltd",
    "Shree Ganesh Forgings Ltd", "Shree Manufacturing Company Ltd", "Shree Nidhi Trading Co. Ltd",
    "Shree Pacetronix Ltd", "Shree Salasar Investments Ltd", "Shreyas Intermediates Ltd",
    "Shri Niwas Leasing And Finance Ltd", "Shricon Industries Ltd",
    "Shriram Asset Management Company Ltd", "Shukra Bullions Ltd", "Shyam Telecom Ltd",
    "Shyama Infosys Ltd", "Shyamkamal Investments Ltd", "Siddha Ventures Ltd", "Sidh Automobiles Ltd",
    "Siel Financial Services Ltd", "Sikozy Realtors Ltd", "Silicon Valley Infotech Ltd",
    "Silver Oak India Ltd", "Silveroak Commercials Ltd", "Silverpoint Infratech Ltd",
    "Simplex Mills Company Ltd", "Simplex Papers Ltd", "Specular Marketing & Financing Ltd",
    "Sinnar Bidi Udyog Ltd", "SIP Industries Ltd", "Sir Shadi Lal Enterprises Ltd",
    "Sita Shree Food Products Ltd", "Skyline Ventures India Ltd", "SM Energy Teknik & Electronics Ltd",
    "Smiths & Founders (India) Ltd", "SMS Techsoft (India) Ltd", "Sobhagya Mercantile Ltd",
    "Sofcom Systems Ltd", "Softbpo Global Services Ltd", "Solid Carbide Tools Ltd",
    "Solis Marketing Ltd", "Soma Textiles & Industries Ltd", "Sonal Adhesives Ltd",
    "Soni Medicare Ltd", "Source Industries (India) Ltd", "South Asian Enterprises Ltd",
    "Southern Ispat and Energy Ltd", "Southern Latex Ltd", "Southern Online Bio Technologies Ltd",
    "Sowbhagya Media Ltd", "SP Capital Financing Ltd", "Sparc Systems Ltd",
    "Sparkling (India) Finshares Ltd", "Speciality Papers Ltd", "Spectra Industries Ltd",
    "Spectrum Foods Ltd", "Suvidha Infraestate Corporation Ltd", "Spentex Industries Ltd",
    "Spice Islands Apparels Ltd", "Spring Fields Infraventure Ltd", "Square Four Projects India Ltd",
    "SR Industries Ltd", "Cella Space Ltd", "Sreechem Resins Ltd",
    "Sri Lakshmi Saraswathi Textiles Arni Ltd", "Sri Ramakrishna Mills Coimbatore Ltd",
    "Sri Vajra Granites Ltd", "SRM Energy Ltd", "SS Organics Ltd",
    "Standard Shoe Sole and Mould (India) Ltd", "Starlit Power Systems Ltd",
    "Steel Strips Infrastructures Ltd", "Steelco Gujarat Ltd", "Stellant Securities (India) Ltd",
    "Sterling Guaranty & Finance Ltd", "Sterling Powergensys Ltd", "Subhash Silk Mills Ltd",
    "Sudal Industries Ltd", "Sujala Trading & Holdings Ltd", "Sujana Universal Industries Ltd",
    "Sumeru Industries Ltd", "Sun Source India Ltd", "Sunbright Stock Broking Ltd",
    "Sungold Capital Ltd", "Sunitee Chemicals Ltd", "Sunraj Diamond Exports Ltd",
    "Super Domestic Machines Ltd", "Superb Papers Ltd", "Superior Finlease Ltd",
    "Supra Pacific Management Consultancy Ltd", "Supra Trends Ltd", "Supremex Shine Steels Ltd",
    "Surana Corporation Ltd", "Suryachakra Power Corporation Ltd", "Suryakrupa Finance Ltd",
    "Suryo Foods & Industries Ltd", "Terraform Magnum Ltd", "SVA India Ltd", "Svarnim Trade Udyog Ltd",
    "Swagruha Infrastructure Ltd", "Swarna Securities Ltd", "Sword & Shield Pharma Ltd",
    "Syncom Healthcare Ltd", "T Spiritual World Ltd", "Tamilnadu Jai Bharath Mills Ltd",
    "Tara Jewels Ltd", "Tarai Foods Ltd", "TCI Industries Ltd", "Terraform Realstate Ltd",
    "Tivoli Construction Ltd", "Thakral Services India Ltd", "Thambbi Modern Spinning Mills Ltd",
    "Thirdwave Financial Intermediaries Ltd", "Thomas Scott (India) Ltd", "Tirupati Fincorp Ltd",
    "Tirupati Tyres Ltd", "Transoceanic Properties Ltd", "Total Exports Ltd", "Towa Sokki Ltd",
    "TPI India Ltd", "Trans Asia Corporation Ltd", "Trans Financial Resources Ltd",
    "Trans Freight Containers Ltd", "Transglobe Foods Ltd", "Twin Roses Trades & Agencies Ltd",
    "TRC Financial Services Ltd", "Tribhuvan Housing Ltd", "Tricom Fruit Products Ltd",
    "Trident Tools Ltd", "Trijal Industries Ltd", "Trimurthi Ltd", "Trishakti Electronics & Industries Ltd",
    "Triton Corp Ltd", "Triveni Enterprises Ltd", "Trombo Extractions Ltd", "TSL Industries Ltd",
    "Tulasee Bio Ethanol Ltd", "Tulip Star Hotels Ltd", "Tulsi Extrusions Ltd",
    "Modulex Construction Technologies Ltd", "Tuticorin Alkali Chemicals & Fertilisers Ltd",
    "Pulsar International Ltd", "Typhoon Financial Services Ltd", "Typhoon Holdings Ltd",
    "Sagar Systech Ltd", "United Textiles Ltd", "Unity Infraprojects Ltd", "Universal Arts Ltd",
    "Shikhar Leasing & Trading Ltd", "Uniworth Ltd", "USG Tech Solutions Ltd", "Ushdev International Ltd",
    "Usher Agro Ltd", "Vaishno Cement Company Ltd", "Vallabh Poly Plast International Ltd",
    "Vani Commercials Ltd", "Vantage Knowledge Academy Ltd", "Vardhaman Laboratories Ltd",
    "Vardhman Concrete Ltd", "Vardhman Polytex Ltd", "Vas Infrastructure Ltd",
    "Vax Housing Finance Corporation Ltd", "VCCL Ltd", "VCK Capital Market Services Ltd",
    "Venlon Enterprises Ltd", "Ventura Textiles Ltd", "Venus Universal Ltd", "Vertical Industries Ltd",
    "Viceroy Hotels Ltd", "Victory Paper & Boards India Ltd", "Vikalp Securities Ltd",
    "Vimal Oil & Foods Ltd", "Vinaditya Trading Company Ltd", "Vintage Securities Ltd",
    "Vintron Informatics Ltd", "Virgo Global Ltd", "Virtualsoft Systems Ltd", "Visco Trade Associates Ltd",
    "Vishvprabha Ventures Ltd", "Vision Cinemas Ltd", "Vistar Amar Ltd", "Visu International Ltd",
    "Vitan Agro Industries Ltd", "Vivanza Biosciences Ltd", "Voltaire Leasing & Finance Ltd",
    "VR Woodart Ltd", "VSF Projects Ltd", "W. S. Industries (India) Ltd",
    "Welcure Drugs & Pharmaceuticals Ltd", "Wellesley Corporation Ltd", "Welterman International Ltd",
    "Williamson Financial Services Ltd", "Winsome Diamonds and Jewellery Ltd",
    "Winy Commercial & Fiscal Services Ltd", "Wisec Global Ltd", "Women Networks Ltd",
    "Sindu Valley Technologies Ltd", "Worth Investment & Trading Co Ltd", "XL Energy Ltd",
    "Yantra Natural Resources Ltd", "Yarn Syndicate Ltd", "Sunedison Infrastructure Ltd",
    "Yuranus Infrastructure Ltd", "Yuvraaj Hygiene Products Ltd", "Zenith Birla (India) Ltd",
    "Zenith Capitals Ltd", "Zicom Electronic Security Systems Ltd", "Zylog Systems Ltd"
  ],
  NSE: [
    "20 Microns Limited", "21st Century Management Services Limited", "360 ONE WAM LIMITED", "3i Infotech Limited",
    "3M India Limited", "3P Land Holdings Limited", "5Paisa Capital Limited", "63 moons technologies limited",
    "A2Z Infra Engineering Limited", "AAA Technologies Limited", "Aadhar Housing Finance Limited", "Aakash Exploration Services Limited",
    "Aarey Drugs & Pharmaceuticals Limited", "Aarnav Fashions Limited", "Aaron Industries Limited", "Aartech Solonics Limited",
    "Aarti Drugs Limited", "Aarti Industries Limited", "Aarti Pharmalabs Limited", "Aarti Surfactants Limited",
    "Aarvi Encon Limited", "Aavas Financiers Limited", "ABB India Limited", "Abbott India Limited",
    "Aditya Birla Capital Limited", "A B Cotspin India Limited", "Allied Blenders and Distillers Limited", "Aditya Birla Fashion and Retail Limited",
    "A B Infrabuild Limited", "Aditya Birla Lifestyle Brands Limited", "ABM International Limited", "Aditya Birla Real Estate Limited",
    "Aditya Birla Sun Life AMC Limited", "ACC Limited", "Accelya Solutions India Limited", "Accuracy Shipping Limited",
    "Action Construction Equipment Limited", "Ace Integrated Solutions Limited", "Archean Chemical Industries Limited", "Andhra Cements Limited",
    "Acme Solar Holdings Limited", "Acutaas Chemicals Limited", "Adani Energy Solutions Limited", "Adani Enterprises Limited",
    "Adani Green Energy Limited", "Adani Ports and Special Economic Zone Limited", "Adani Power Limited", "ADF Foods Limited",
    "Archidply Decor Limited", "Ador Welding Limited", "Adroit Infotech Limited", "Allied Digital Services Limited",
    "Advait Energy Transitions Limited", "Advance Agrolife Limited", "Advani Hotels & Resorts (India) Limited", "Advent Hotels International Limited",
    "Advanced Enzyme Technologies Limited", "Aegis Logistics Limited", "Aegis Vopak Terminals Limited", "Artemis Electricals and Projects Limited",
    "Aequs Limited", "Aeroflex Enterprises Limited", "Aeroflex Industries Limited", "Aeroflex Neu Limited",
    "Aether Industries Limited", "Afcons Infrastructure Limited", "Affle 3i Limited", "Affordable Robotic & Automation Limited",
    "Akme Fintrade (India) Limited", "Abans Financial Services Limited", "Agarwal Industrial Corporation Limited", "Dr. Agarwal's Health Care Limited",
    "AGI Greenpac Limited", "Agi Infra Limited", "Agri-Tech (India) Limited", "Agro Phos India Limited",
    "AGS Transact Technologies Limited", "Anlon Healthcare Limited", "Ahlada Engineers Limited", "Asian Hotels (East) Limited",
    "Ahluwalia Contracts (India) Limited", "AIA Engineering Limited", "Authum Investment & Infrastructure Limited", "Airan Limited",
    "Airo Lam limited", "Ajanta Pharma Limited", "Ajax Engineering Limited", "Ajmera Realty & Infra India Limited",
    "Ajooni Biotech Limited", "Akash Infra-Projects Limited", "Akg Exim Limited", "AKI India Limited",
    "Akshar Spintex Limited", "AksharChem India Limited", "Aksh Optifibre Limited", "Akums Drugs and Pharmaceuticals Limited",
    "Akzo Nobel India Limited", "Alankit Limited", "Albert David Limited", "Alembic Limited",
    "Algoquant Fintech Limited", "Alicon Castalloy Limited", "Alivus Life Sciences Limited", "Alkali Metals Limited",
    "Alkem Laboratories Limited", "Alkyl Amines Chemicals Limited", "Allcargo Logistics Limited", "Alldigi Tech Limited",
    "All Time Plastics Limited", "Almondz Global Securities Limited", "Alok Industries Limited", "Alpa Laboratories Limited",
    "Alphageo (India) Limited", "Amagi Media Labs Limited", "Amanta Healthcare Limited", "Amber Enterprises India Limited",
    "Ambica Agarbathies & Aroma industries Limited", "Ambika Cotton Mills Limited", "Ambuja Cements Limited", "AMD Industries Limited",
    "Amj Land Holdings Limited", "Amines & Plasticizers Limited", "Amrutanjan Health Care Limited", "Anand Rathi Wealth Limited",
    "Anant Raj Limited", "ANDHRA PAPER LIMITED", "The Andhra Sugars Limited", "Angel One Limited",
    "Anik Industries Limited", "Ankit Metal & Power Limited", "Anmol India Limited", "Ansal Properties & Infrastructure Limited",
    "Antelopus Selan Energy Limited", "Antarctica Limited", "Anthem Biosciences Limited", "Anuh Pharma Limited",
    "The Anup Engineering Limited", "Anupam Rasayan India Limited", "Apar Industries Limited", "Anjani Portland Cement Limited",
    "Apcotex Industries Limited", "Apex Frozen Foods Limited", "APL Apollo Tubes Limited", "Alembic Pharmaceuticals Limited",
    "Apollo Micro Systems Limited", "Apollo Hospitals Enterprise Limited", "Apollo Pipes Limited", "Apollo Tyres Limited",
    "Apollo Sindoori Hotels Limited", "Aptech Limited", "Aptus Value Housing Finance India Limited", "Aqylon Nexus Limited",
    "Archidply Industries Limited", "Archies Limited", "Amara Raja Energy & Mobility Limited", "Rajdarshan Industries Limited",
    "Arfin India Limited", "Aries Agro Limited", "Arihant Capital Markets Limited", "Arihant Superstructures Limited",
    "Arisinfra Solutions Limited", "Arkade Developers Limited", "Arman Financial Services Limited", "Aro Granite Industries Limited",
    "Arrow Greentech Limited", "Anand Rathi Share and Stock Brokers Limited", "Artemis Medicare Services Limited", "Art Nirman Limited",
    "Arvee Laboratories (India) Limited", "Arvind Limited", "Arvind Fashions Limited", "Arvind SmartSpaces Limited",
    "Asahi India Glass Limited", "Asahi Songwon Colors Limited", "Automotive Stampings and Assemblies Limited", "Associated Alcohols & Breweries Ltd.",
    "Ashapura Minechem Limited", "Ashiana Housing Limited", "Ashima Limited", "Ashoka Buildcon Limited",
    "Ashoka Metcast Limited", "Ashok Leyland Limited", "Asian Energy Services Limited", "Asian Hotels (North) Limited",
    "Asian Paints Limited", "Asian Granito India Limited", "ASK Automotive Limited", "Bartronics India Limited",
    "Aspinwall and Company Limited", "Astec LifeSciences Limited", "Aster DM Healthcare Limited", "Astral Limited",
    "Astra Microwave Products Limited", "AstraZeneca Pharma India Limited", "Astron Paper & Board Mill Limited", "Atal Realtech Limited",
    "Atam Valves Limited", "Adani Total Gas Limited", "Ather Energy Limited", "Allcargo Terminals Limited",
    "ATLANTAA LIMITED", "Atlanta Electricals Limited", "Atlas Cycles (Haryana) Limited", "Atul Limited",
    "Atul Auto Limited", "AU Small Finance Bank Limited", "Auri Grow India Limited", "Aurionpro Solutions Limited",
    "Aurobindo Pharma Limited", "Aurum PropTech Limited", "Ausom Enterprise Limited", "Automotive Axles Limited",
    "Autoline Industries Limited", "Avadh Sugar & Energy Limited", "Avalon Technologies Limited", "Avantel Limited",
    "Avanti Feeds Limited", "AVG Logistics Limited", "Aditya Vision Limited", "Avonmore Capital & Management Services Limited",
    "AVRO INDIA LIMITED", "AVT Natural Products Limited", "Awfis Space Solutions Limited", "Antony Waste Handling Cell Limited",
    "AWL Agri Business Limited", "Axis Bank Limited", "AXISCADES Technologies Limited", "Axita Cotton Limited",
    "Aye Finance Limited", "AYM Syntex Limited", "Azad Engineering Limited", "Bafna Pharmaceuticals Limited",
    "B.A.G Films and Media Limited", "Baid Finserv Limited", "Bajaj Auto Limited", "Bajaj Consumer Care Limited",
    "Bajaj Electricals Limited", "Bajaj Finserv Limited", "Bajaj Healthcare Limited", "Bajaj Housing Finance Limited",
    "Bajaj Hindusthan Sugar Limited", "Bajaj Holdings & Investment Limited", "Indef Manufacturing Limited", "Bajel Projects Limited",
    "Bajaj Finance Limited", "Shree Tirupati Balajee Agro Trading Company Limited", "Balaji Telefilms Limited", "Balaji Amines Limited",
    "BALAXI PHARMACEUTICALS LIMITED", "Balkrishna Paper Mills Limited", "Balkrishna Industries Limited", "Balmer Lawrie & Company Limited",
    "Bal Pharma Limited", "Balrampur Chini Mills Limited", "Balu Forge Industries Limited", "Banaras Beads Limited",
    "Bannari Amman Sugars Limited", "Banco Products (I) Limited", "Bandhan Bank Limited", "Bang Overseas Limited",
    "Banka BioLoo Limited", "Bank of Baroda", "Bank of India", "Bansal Wire Industries Limited",
    "Banswara Syntex Limited", "BASF India Limited", "Bannari Amman Spinning Mills Limited", "Bata India Limited",
    "Bayer Cropscience Limited", "Bharat Bijlee Limited", "Black Box Limited", "The Bombay Burmah Trading Corporation Limited",
    "B&B Triplewall Containers Limited", "Brightcom Group Limited", "Bcl Industries Limited", "Brand Concepts Limited",
    "Bharat Dynamics Limited", "Beardsell Limited", "Mrs. Bectors Food Specialities Limited", "Bedmutha Industries Limited",
    "Bharat Electronics Limited", "Bella Casa Fashion & Retail Limited", "Belrise Industries Limited", "BEML Limited",
    "Bhansali Engineering Polymers Limited", "Berger Paints (I) Limited", "Best Agrolife Limited", "Beta Drugs Limited",
    "BF Investment Limited", "BF Utilities Limited", "BGR Energy Systems Limited", "Bhagiradha Chemicals & Industries Limited",
    "Bhageria Industries Limited", "Bhagyanagar India Limited", "Bhandari Hosiery Exports Limited", "Bharat Coking Coal Limited",
    "Bharat Forge Limited", "Bharat Gears Limited", "Bharat Rasayan Limited", "Bharat Seats Limited",
    "Bharat Wire Ropes Limited", "Bharti Airtel Limited", "Bharti Hexacom Limited", "Bharat Heavy Electricals Limited",
    "Bigbloc Construction Limited", "Bikaji Foods International Limited", "Bhartiya International Limited", "BIL VYAPAR LIMITED",
    "Biocon Limited", "Biofil Chemicals & Pharmaceuticals Limited", "Birla Cable Limited", "Birla Corporation Limited",
    "Aditya Birla Money Limited", "BirlaNu Limited", "BLACKBUCK LIMITED", "BEML Land Assets Limited",
    "BLB Limited", "Bliss GVS Pharma Limited", "B. L. Kashyap and Sons Limited", "BLS International Services Limited",
    "BLS E-Services Limited", "Blue Coast Hotels Limited", "Blue Dart Express Limited", "Blue Jet Healthcare Limited",
    "Blue Star Limited", "BlueStone Jewellery and Lifestyle Limited", "Bluspring Enterprises Limited", "BMW Ventures Limited",
    "Bodal Chemicals Limited", "Bohra Industries Limited", "Bombay Dyeing & Mfg Company Limited", "Bonlon Industries Limited",
    "Borana Weaves Limited", "Borosil Limited", "BOROSIL RENEWABLES LIMITED", "Borosil Scientific Limited",
    "BOSCH HOME COMFORT INDIA LIMITED", "Bosch Limited", "Bharat Petroleum Corporation Limited", "BPL Limited",
    "Brigade Enterprises Limited", "Brigade Hotel Ventures Limited", "Britannia Industries Limited", "Bharat Road Network Limited",
    "Brooks Laboratories Limited", "BSE Limited", "Bombay Super Hybrid Seeds Limited", "BSL Limited",
    "BIRLASOFT LIMITED", "Bodhi Tree Multimedia Limited", "Shankara Buildpro Limited", "Butterfly Gandhimathi Appliances Limited",
    "Barak Valley Cements Limited", "The Byke Hospitality Ltd", "California Software Company Limited", "Camlin Fine Sciences Limited",
    "Campus Activewear Limited", "Computer Age Management Services Limited", "Canara Bank", "Can Fin Homes Limited",
    "Canara HSBC Life Insurance Company Limited", "Cantabil Retail India Limited", "Capacit'e Infraprojects Limited", "Capillary Technologies India Limited",
    "Capital Small Finance Bank Limited", "Caplin Point Laboratories Limited", "Capital Trust Limited", "Carborundum Universal Limited",
    "CARE Ratings Limited", "Carraro India Limited", "Cartrade Tech Limited", "CARYSIL LIMITED",
    "Castrol India Limited", "AvenuesAI Limited", "Consolidated Construction Consortium Limited", "Country Club Hospitality & Holidays Limited",
    "CCL Products (India) Limited", "Central Depository Services (India) Limited", "CEAT Limited", "Ceigall India Limited",
    "Ceinsys Tech Limited", "Celebrity Fashions Limited", "Cello World Limited", "Cemindia Projects Limited",
    "Century Enka Limited", "Century Extrusions Limited", "Central Bank of India", "Centrum Capital Limited",
    "Centum Electronics Limited", "Century Plyboards (India) Limited", "Cera Sanitaryware Limited", "Cerebra Integrated Technologies Limited",
    "CESC Limited", "Concord Enviro Systems Limited", "Capri Global Capital Limited", "CG Power and Industrial Solutions Limited",
    "Chalet Hotels Limited", "Chambal Fertilizers & Chemicals Limited", "Chembond Material Technologies Limited", "Chembond Chemicals Limited",
    "Chemcon Speciality Chemicals Limited", "Chemfab Alkalis Limited", "Chemplast Sanmar Limited", "Chennai Petroleum Corporation Limited",
    "Cheviot Company Limited", "Choice International Limited", "Cholamandalam Investment and Finance Company Limited", "Cholamandalam Financial Holdings Limited",
    "CIE Automotive India Limited", "Capital India Finance Limited", "Cigniti Technologies Limited", "Cineline India Limited",
    "Cinevista Limited", "Cipla Limited", "Clean Science and Technology Limited", "Clean Max Enviro Energy Solutions Limited",
    "CL Educate Limited", "Chaman Lal Setia Exports Limited", "CMS Info Systems Limited", "Creative Newtech Limited",
    "Coal India Limited", "Coastal Corporation Limited", "Cochin Shipyard Limited", "Coffee Day Enterprises Limited",
    "Coforge Limited", "Cohance Lifesciences Limited", "Colgate Palmolive (India) Limited", "Compuage Infocom Limited",
    "Compucom Software Limited", "Commercial Syn Bags Limited", "Container Corporation of India Limited", "Concord Biotech Limited",
    "Confidence Petroleum India Limited", "Consolidated Finvest & Holdings Limited", "Control Print Limited", "Coral India Finance & Housing Limited",
    "Cords Cable Industries Limited", "Coromandel International Limited", "CORONA Remedies Limited", "COSMO FIRST LIMITED",
    "Country Condo's Limited", "CP Capital Limited", "Career Point Edutech Limited", "Aditya Infotech Limited",
    "Craftsman Automation Limited", "Canara Robeco Asset Management Company Limited", "Creative Eye Limited", "CREDITACCESS GRAMEEN LIMITED",
    "Crest Ventures Limited", "CRISIL Limited", "Crizac Limited", "Crompton Greaves Consumer Electricals Limited",
    "Crown Lifters Limited", "CSB Bank Limited", "CSL Finance Limited", "Cambridge Technology Enterprises Limited",
    "City Union Bank Limited", "Cubex Tubings Limited", "Cummins India Limited", "Cupid Limited",
    "Cura Technologies Limited", "Cyber Media (India) Limited", "Cybertech Systems And Software Limited", "Cyient Limited",
    "Cyient DLM Limited", "Dabur India Limited", "Dalmia Bharat Limited", "Dalmia Bharat Sugar and Industries Limited",
    "Dam Capital Advisors Limited", "Damodar Industries Limited", "Dangee Dums Limited", "Datamatics Global Services Limited",
    "Data Patterns (India) Limited", "Davangere Sugar Company Limited", "D.B.Corp Limited", "Deepak Builders & Engineers India Limited",
    "Dilip Buildcon Limited", "Dhampur Bio Organics Limited", "Valor Estate Limited", "DB (International) Stock Brokers Limited",
    "Dishman Carbogen Amcis Limited", "DCB Bank Limited", "Dc Infotech And Communication Limited", "DCM  Limited",
    "DCM Financial Services Limited", "DCM Nouvelle Limited", "DCM Shriram Limited", "DCM Shriram International Limited",
    "DCM Shriram Industries Limited", "DCW Limited", "DCX Systems Limited", "Ddev Plastiks Industries Limited",
    "Deccan Cements Limited", "DEE Development Engineers Limited", "Deepak Fertilizers and Petrochemicals Corporation Limited", "Deepak Nitrite Limited",
    "Deep Industries Limited", "Delhivery Limited", "DELPHI WORLD MONEY LIMITED", "Delta Corp Limited",
    "Delta Manufacturing Limited", "Den Networks Limited", "De Nora India Limited", "Denta Water and Infra Solutions Limited",
    "Dev Information Technology Limited", "Dev Accelerator Limited", "Devyani International Limited", "Digicontent Limited",
    "Dhampur Sugar Mills Limited", "Dhanlaxmi Bank Limited", "Dhanuka Agritech Limited", "DHARAN INFRA-EPC LIMITED",
    "Dharmaj Crop Guard Limited", "Dhruv Consultancy Services Limited", "Dhunseri Investments Limited", "Diamond Power Infrastructure Limited",
    "Diamines & Chemicals Limited", "Prataap Snacks Limited", "DIC India Limited", "Diffusion Engineers Limited",
    "Digidrive Distributors Limited", "DiGiSPICE Technologies Limited", "Digitide Solutions Limited", "Digjam Limited",
    "Dish TV India Limited", "Divgi Torqtransfer Systems Limited", "Divi's Laboratories Limited", "Dixon Technologies (India) Limited",
    "DJ Mediaprint & Logistics Limited", "DLF Limited", "D-Link (India) Limited", "Avenue Supermarts Limited",
    "DMCC SPECIALITY CHEMICALS LIMITED", "Diligent Media Corporation Limited", "Dodla Dairy Limited", "Dolat Algotech Limited",
    "Dollar Industries Limited", "Dolphin Offshore Enterprises (India) Limited", "DOMS Industries Limited", "Donear Industries Limited",
    "D. P. Abhushan Limited", "DPSC Limited", "D P Wires Limited", "DRC Systems India Limited",
    "Dreamfolks Services Limited", "Dredging Corporation of India Limited", "Dr. Reddy's Laboratories Limited", "DCM Shriram Fine Chemicals Limited",
    "Dynacons Systems & Solutions Limited", "Dhunseri Tea & Industries Limited", "Ducon Infratechnologies Limited", "Dhunseri Ventures Limited",
    "Dwarikesh Sugar Industries Limited", "Dynamic Cables Limited", "Dynamatic Technologies Limited", "Dynemic Products Limited",
    "E2E Networks Limited", "Easy Trip Planners Limited", "GNG Electronics Limited", "eClerx Services Limited",
    "Ecos (India) Mobility & Hospitality Limited", "Edelweiss Financial Services Limited", "EFC (I) Limited", "Eicher Motors Limited",
    "EID Parry India Limited", "Enviro Infra Engineers Limited", "Euro India Fresh Foods Limited", "EIH Associated Hotels Limited",
    "EIH Limited", "Eimco Elecon (India) Limited", "Everest Kanto Cylinder Limited", "Eldeco Housing And Industries Limited",
    "Elecon Engineering Company Limited", "Electrosteel Castings Limited", "Electrotherm (India) Limited", "Elgi Equipments Limited",
    "Elgi Rubber Company Limited", "Elin Electronics Limited", "Ellenbarrie Industrial Gases Limited", "Emami Limited",
    "Emami Paper Mills Limited", "Emami Realty Limited", "Embassy Developments Limited", "Emcure Pharmaceuticals Limited",
    "Electronics Mart India Limited", "Emkay Global Financial Services Limited", "Emmbi Industries Limited", "Emmvee Photovoltaic Power Limited",
    "EMS Limited", "eMudhra Limited", "Endurance Technologies Limited", "Energy Development Company Limited",
    "Engineers India Limited", "Entertainment Network (India) Limited", "Siemens Energy India Limited", "Entero Healthcare Solutions Limited",
    "EPACK Durable Limited", "EPack Prefab Technologies Limited", "Epigral Limited", "EPL Limited",
    "Equippp Social Impact Technologies Limited", "Equitas Small Finance Bank Limited", "Eris Lifesciences Limited", "Esab India Limited",
    "ESAF Small Finance Bank Limited", "Escorts Kubota Limited", "Essar Shipping Limited", "Integra Essentia Limited",
    "Ester Industries Limited", "ETERNAL LIMITED", "Ethos Limited", "Eureka Forbes Limited",
    "Euro Panel Products Limited", "Euro Pratik Sales Limited", "Eurotex Industries and Exports Limited", "Eveready Industries India Limited",
    "Everest Industries Limited", "Excel Realty N Infra Limited", "Excel Industries Limited", "Excelsoft Technologies Limited",
    "Exicom Tele-Systems Limited", "Exide Industries Limited", "Expleo Solutions Limited", "Exxaro Tiles Limited",
    "Fabtech Technologies Limited", "Fertilizers and Chemicals Travancore Limited", "Fairchem Organics Limited", "Faze Three Limited",
    "Fineotex Chemical Limited", "FCS Software Solutions Limited", "FDC Limited", "The Federal Bank  Limited",
    "Fedbank Financial Services Limited", "Future Enterprises Limited", "Future Enterprises Limited", "Fiberweb (India) Limited",
    "Fiem Industries Limited", "Filatex India Limited", "Filatex Fashions Limited", "Finolex Cables Limited",
    "Fine Organic Industries Limited", "Finkurve Financial Services Limited", "Fino Payments Bank Limited", "Finolex Industries Limited",
    "Brainbees Solutions Limited", "Fischer Medical Ventures Limited", "Five-Star Business Finance Limited", "Flair Writing Industries Limited",
    "Flexituff Ventures International Limited", "Future Lifestyle Fashions Limited", "Gujarat Fluorochemicals Limited", "Federal-Mogul Goetze (India) Limited.",
    "Future Market Networks Limited", "Focus Lighting and Fixtures Limited", "Foods & Inns Limited", "FORCE MOTORS LTD",
    "Fortis Healthcare Limited", "Foseco India Limited", "Fractal Analytics Limited", "Firstsource Solutions Limited",
    "Fusion Finance Limited", "Gabriel India Limited", "Gujarat Ambuja Exports Limited", "GAIL (India) Limited",
    "Gala Precision Engineering Limited", "Galaxy Surfactants Limited", "Gallantt Ispat Limited", "Gandhar Oil Refinery (India) Limited",
    "Gandhi Special Tubes Limited", "Ganesha Ecosphere Limited", "Ganesh Benzoplast Limited", "Ganesh Consumer Products Limited",
    "GANESH HOUSING LIMITED", "Ganga Forging Limited", "Ganges Securities Limited", "Garware Technical Fibres Limited",
    "Garuda Construction and Engineering Limited", "GACM Technologies Limited", "GACM Technologies Limited", "Gateway Distriparks Limited",
    "Gaudium IVF and Women Health Limited", "Gayatri Highways Limited", "Gretex Corporate Services Limited", "GeeCee Ventures Limited",
    "Geekay Wires Limited", "Gem Aromatics Limited", "Generic Engineering Construction and Projects Limited", "Genesys International Corporation Limited",
    "Genus Paper & Boards Limited", "Genus Power Infrastructures Limited", "Geojit Financial Services Limited", "The Great Eastern Shipping Company Limited",
    "GFL Limited", "GHCL Limited", "GHCL Textiles Limited", "GIC Housing Finance Limited",
    "Globe International Carriers Limited", "General Insurance Corporation of India", "Gillanders Arbuthnot & Company Limited", "Gillette India Limited",
    "Ginni Filaments Limited", "Gujarat Industries Power Company Limited", "GK Energy Limited", "Gujarat Kidney And Super Speciality Limited",
    "GKW Limited", "Gland Pharma Limited", "GlaxoSmithKline Pharmaceuticals Limited", "Glenmark Pharmaceuticals Limited",
    "Gujarat Lease Financing Limited", "Global Education Limited", "Globale Tessile Limited", "Global Vectra Helicorp Limited",
    "GLOBE ENTERPRISES (INDIA) LIMITED", "Globe Civil Projects Limited", "Globus Spirits Limited", "Gloster Limited",
    "Glottis Limited", "GM Breweries Limited", "Gujarat Mineral Development Corporation Limited", "GMM Pfaudler Limited",
    "GMR AIRPORTS LIMITED", "GMR Power and Urban Infra Limited", "GNA Axles Limited", "Gujarat Narmada Valley Fertilizers and Chemicals Limited",
    "Goa Carbon Limited", "GOCL Corporation Limited", "Go Fashion (India) Limited", "Godavari Biorefineries Limited",
    "Godfrey Phillips India Limited", "Go Digit General Insurance Limited", "Godrej Agrovet Limited", "Godrej Consumer Products Limited",
    "Godrej Industries Limited", "Godrej Properties Limited", "Gokaldas Exports Limited", "Gokul Refoils and Solvent Limited",
    "Gokul Agro Resources Limited", "Golden Tobacco Limited", "Goldiam International Limited", "AION-TECH SOLUTIONS LIMITED",
    "Goodluck India Limited", "Gopal Snacks Limited", "Goyal Aluminiums Limited", "Godawari Power And Ispat limited",
    "Gujarat Pipavav Port Limited", "GPT Healthcare Limited", "GPT Infraprojects Limited", "Granules India Limited",
    "Graphite India Limited", "Grasim Industries Limited", "Gravita India Limited", "Greaves Cotton Limited",
    "Greenlam Industries Limited", "Greenpanel Industries Limited", "Greenply Industries Limited", "Orient Green Power Company Limited",
    "Grindwell Norton Limited", "G R Infraprojects Limited", "GRM Overseas Limited", "The Grob Tea Company Limited",
    "Billionbrains Garage Ventures Limited", "GRP Limited", "Garden Reach Shipbuilders & Engineers Limited", "Garware Hi-Tech Films Limited",
    "Gujarat State Fertilizers & Chemicals Limited", "Global Surfaces Limited", "GSP Crop Science Limited", "Gujarat State Petronet Limited",
    "GSS Infotech Limited", "G-TEC JAINX EDUCATION LIMITED", "GTL Limited", "GTL Infrastructure Limited",
    "GTPL Hathway Limited", "Gufic Biosciences Limited", "Gujarat Alkalies and Chemicals Limited", "Gujarat Apollo Industries Limited",
    "Gujarat Gas Limited", "Gujarat Raffia Industries Limited", "Gujarat Themis Biosyn Limited", "Gulf Oil Lubricants India Limited",
    "GP Petroleums Limited", "Gulshan Polyols Limited", "GVK Power & Infrastructure Limited", "GE Power India Limited",
    "GVP Infotech Limited", "GE Vernova T&D India Limited", "Hindustan Aeronautics Limited", "Halder Venture Limited",
    "HALEOS LABS LIMITED", "Happiest Minds Technologies Limited", "Happy Forgings Limited", "Hardwyn India Limited",
    "Hariom Pipe Industries Limited", "Harrisons  Malayalam Limited", "Harsha Engineers International Limited", "Hathway Cable & Datacom Limited",
    "Hatsun Agro Product Limited", "Havells India Limited", "Sri Havisha Hospitality and Infrastructure Limited", "HBL Engineering Limited",
    "HB Stockholdings Limited", "Hindustan Construction Company Limited", "Healthcare Global Enterprises Limited", "HCL Infosystems Limited",
    "HCL Technologies Limited", "HDB Financial Services Limited", "HDFC Asset Management Company Limited", "HDFC Bank Limited",
    "HDFC Life Insurance Company Limited", "Heads UP Ventures Limited", "HEC Infra Projects Limited", "HEG Limited",
    "HeidelbergCement India Limited", "Hemisphere Properties India Limited", "Heranba Industries Limited", "Heritage Foods Limited",
    "Hero MotoCorp Limited", "Hester Biosciences Limited", "Hexa Tradex Limited", "Hexaware Technologies Limited",
    "HFCL Limited", "H.G. Infra Engineering Limited", "HandsOn Global Management (HGM) Limited", "Hinduja Global Solutions Limited",
    "Hikal Limited", "Highway Infrastructure Limited", "Hilton Metal Forging Limited", "Himatsingka Seide Limited",
    "Hindalco Industries Limited", "Hindustan Composites Limited", "Hindcon Chemicals Limited", "Hindustan Copper Limited",
    "Hindustan Oil Exploration Company Limited", "Hindustan Petroleum Corporation Limited", "Hindustan Unilever Limited",
    "Hindware Home Innovation Limited", "Hindustan Zinc Limited", "Hind Rectifiers Limited", "Hisar Metal Industries Limited",
    "Hi-Tech Pipes Limited", "Hitech Corporation Limited", "The Hi-Tech Gears Limited", "HLE Glascoat Limited",
    "HLV LIMITED", "HMA Agro Industries Limited", "HMT Limited", "Hindustan Media Ventures Limited",
    "Hindustan Foods Limited", "Home First Finance Company India Limited", "Honasa Consumer Limited", "Honeywell Automation India Limited",
    "Honda India Power Products Limited", "HP Adhesives Limited", "Hindprakash Industries Limited", "HPL Electric & Power Limited",
    "Himadri Speciality Chemical Limited", "HT Media Limited", "Hubtown Limited", "Housing & Urban Development Corporation Limited",
    "Huhtamaki India Limited", "Hybrid Financial Services Limited", "Hyundai Motor India Limited", "Indiabulls Limited",
    "ICDS Limited", "Ice Make Refrigeration Limited", "ICICI Prudential Asset Management Company Limited", "ICICI Bank Limited",
    "ICICI Lombard General Insurance Company Limited", "ICICI Prudential Life Insurance Company Limited", "Indo Count Industries Limited", "ICRA Limited",
    "IDBI Bank Limited", "Vodafone Idea Limited", "Ideaforge Technology Limited", "IDFC First Bank Limited",
    "Indian Energy Exchange Limited", "IFB Agro Industries Limited", "IFB Industries Limited", "IFCI Limited",
    "IFGL Refractories Limited", "Igarashi Motors India Limited", "Indogulf Cropsciences Limited", "International Gemmological Institute (India) Limited",
    "Indraprastha Gas Limited", "IG Petrochemicals Limited", "IIFL Finance Limited", "IIFL Capital Services Limited",
    "Industrial Investment Trust Limited", "IKIO Technologies Limited", "Inventurus Knowledge Solutions Limited", "IL&FS Engineering and Construction Company Limited",
    "IL&FS Transportation Networks Limited", "Imagicaaworld Entertainment Limited", "Indian Metals & Ferro Alloys Limited", "India Motor Parts and Accessories Limited",
    "Impex Ferro Tech Limited", "Insolation Energy Limited", "INCREDIBLE INDUSTRIES LIMITED", "Indbank Merchant Banking Services Limited",
    "Indegene Limited", "The Indian Hotels Company Limited", "The India Cements Limited", "India Glycols Limited",
    "Indiamart Intermesh Limited", "Indian Bank", "Indian Card Clothing Company Limited", "Indian Hume Pipe Company Limited",
    "India Shelter Finance Corporation Limited", "InterGlobe Aviation Limited", "Indigo Paints Limited", "Indiqube Spaces Limited",
    "India Nippon Electricals Limited", "Indo Amines Limited", "Indo Borax & Chemicals Limited", "Indoco Remedies Limited",
    "Indo Farm Equipment Limited", "Indo Rama Synthetics (India) Limited", "IndoStar Capital Finance Limited", "Indo Tech Transformers Limited",
    "Indo Thai Securities Limited", "Indo Us Biotech Limited", "Indowind Energy Limited", "Indraprastha Medical Corporation Limited",
    "Ind-Swift Laboratories Limited", "Indian Terrain Fashions Limited", "IndusInd Bank Limited", "Indus Towers Limited",
    "InfoBeans Technologies Limited", "Infomedia Press Limited", "Infosys Limited", "Ingersoll Rand (India) Limited",
    "Innova Captab Limited", "Innovana Thinklabs Limited", "Innovision Limited", "Inox Green Energy Services Limited",
    "INOX India Limited", "Inox Wind Limited", "Insecticides (India) Limited", "Inspirisys Solutions Limited",
    "Intellect Design Arena Limited", "Intense Technologies Limited", "Interarch Building Solutions Limited", "International Conveyors Limited",
    "Inventure Growth & Securities Limited", "Indian Overseas Bank", "Indian Oil Corporation Limited", "IOL Chemicals and Pharmaceuticals Limited",
    "ION Exchange (India) Limited", "IPCA Laboratories Limited", "India Pesticides Limited", "IRB Infrastructure Developers Limited",
    "Ircon International Limited", "Indian Railway Catering And Tourism Corporation Limited", "Indian Renewable Energy Development Agency Limited",
    "Indian Railway Finance Corporation Limited", "IRIS RegTech Solutions Limited", "Iris Clothings Limited", "IRM Energy Limited",
    "Intrasoft Technologies Limited", "Isgec Heavy Engineering Limited", "Ishan Dyes and Chemicals Limited", "ITC Limited",
    "ITC Hotels Limited", "India Tourism Development Corporation Limited", "ITI Limited", "Ivalue Infosolutions Limited",
    "IL&FS Investment Managers Limited", "IVP Limited", "Le Travenues Technology Limited", "IZMO Limited",
    "The Jammu & Kashmir Bank Limited", "Jagran Prakashan Limited", "Jagsonpal Pharmaceuticals Limited", "Jai Balaji Industries Limited",
    "Jai Corp Limited", "Jain Resource Recycling Limited", "Nandani Creation Limited", "Jamna Auto Industries Limited",
    "Jaro Institute of Technology Management and Research Limited", "Jash Engineering Limited", "Jayant Agro Organics Limited", "Jay Bharat Maruti Limited",
    "Jaykay Enterprises Limited", "Jayaswal Neco Industries Limited", "Jayshree Tea & Industries Limited", "JB Chemicals & Pharmaceuticals Limited",
    "JBM Auto Limited", "Jet Freight Logistics Limited", "J.G.Chemicals Limited", "JHS Svendgaard Laboratories Limited",
    "Jindal Photo Limited", "Jindal Poly Films Limited", "Jindal Saw Limited", "JINDAL STEEL LIMITED",
    "Jindal Drilling And Industries Limited", "Jindal Worldwide Limited", "Jio Financial Services Limited", "Jain Irrigation Systems Limited",
    "Jain Irrigation Systems Limited", "JITF Infralogistics Limited", "JK Cement Limited", "J.Kumar Infraprojects Limited",
    "Jinkushal Industries Limited", "JK Lakshmi Cement Limited", "JK Paper Limited", "JK Tyre & Industries Limited",
    "Jupiter Life Line Hospitals Limited", "Jullundur Motor Agency (Delhi) Limited", "JM Financial Limited", "JNK India Limited",
    "Jocil Limited", "Jindal Poly Investment and Finance Company Limited", "Jaiprakash Power Ventures Limited", "Jana Small Finance Bank Limited",
    "Jindal Stainless Limited", "Jeena Sikho Lifecare Limited", "JSW Cement Limited", "JSW Energy Limited",
    "JSW Holdings Limited", "JSW Infrastructure Limited", "JSW Steel Limited", "Jtekt India Limited",
    "JTL INDUSTRIES LIMITED", "Jubilant Agri and Consumer Products Limited", "Jubilant Foodworks Limited", "Jubilant Ingrevia Limited",
    "Jubilant Pharmova Limited", "Juniper Hotels Limited", "Just Dial Limited", "Jupiter Wagons Limited",
    "Jyothy Labs Limited", "Jyoti CNC Automation Limited", "Jyoti Structures Limited", "Kabra Extrusion Technik Limited",
    "Kajaria Ceramics Limited", "Kakatiya Cement Sugar & Industries Limited", "Sai Silks (Kalamandir) Limited", "Kalpataru Limited",
    "Kalyani Commercials Limited", "Kalyani Forge Limited", "Kalyan Jewellers India Limited", "Kamat Hotels (I) Limited",
    "Kamdhenu Limited", "Kamdhenu Ventures Limited", "Kanani Industries Limited", "Kanoria Chemicals & Industries Limited",
    "Kanpur Plastipack Limited", "Kansai Nerolac Paints Limited", "Kapston Services Limited", "Karma Energy Limited",
    "Karur Vysya Bank Limited", "Kaushalya Infrastructure Development Corporation Limited", "Kavveri Defence & Wireless Technologies Limited", "Kaya Limited",
    "Kaynes Technology India Limited", "KCP Limited", "KCP Sugar and Industries Corporation Limited", "KDDL Limited",
    "KEC International Limited", "Kirloskar Electric Company Limited", "DSJ Keep Learning Limited", "KEI Industries Limited",
    "Kellton Tech Solutions Limited", "Kernex Microsystems (India) Limited", "Kesoram Industries Limited", "Keynote Financial Services Limited",
    "Kfin Technologies Limited", "Khadim India Limited", "Khaitan Chemicals & Fertilizers Limited", "Khaitan (India) Limited",
    "Khandwala Securities Limited", "Kalyani Investment Company Limited", "Kilitch Drugs (India) Limited", "Krishna Institute of Medical Sciences Limited",
    "Kingfa Science & Technology (India) Limited", "KIOCL Limited", "Kiri Industries Limited", "Kirloskar Brothers Limited",
    "Kirloskar Oil Engines Limited", "Kirloskar Industries Limited", "Kirloskar Pneumatic Company Limited", "Kitex Garments Limited",
    "Kewal Kiran Clothing Limited", "Knowledge Marine & Engineering Works Limited", "K.M.Sugar Mills Limited", "KN Agri Resources Limited",
    "KNR Constructions Limited", "Kohinoor Foods Limited", "Kokuyo Camlin Limited", "Kolte - Patil Developers Limited",
    "Kopran Limited", "Kotak Mahindra Bank Limited", "Kothari Sugars And Chemicals Limited", "Kothari Petrochemicals Limited",
    "Kothari Products Limited", "Kotyark Industries Limited", "K.P. Energy Limited", "KPI Green Energy Limited",
    "Kalpataru Projects International Limited", "KPIT Technologies Limited", "K.P.R. Mill Limited", "KRBL Limited",
    "Krebs Biochemicals and Industries Limited", "Kridhan Infra Limited", "Krishana Phoschem Limited", "Krishival Foods Limited",
    "Krishna Defence And Allied Industries Limited", "Kriti Industries (India) Limited", "Kritika Wires Limited", "Kriti Nutrients Limited",
    "KRN Heat Exchanger and Refrigeration Limited", "Kronox Lab Sciences Limited", "Kross Limited", "Krsnaa Diagnostics Limited",
    "Krystal Integrated Services Limited", "Ksb Limited", "Kaveri Seed Company Limited", "KSH International Limited",
    "Kshitij Polyline Limited", "Kalyani Steels Limited", "Ksolves India Limited", "KSR Footwear Limited",
    "The Karnataka Bank Limited", "Kuantum Papers Limited", "Kwality Wall's (India) Limited", "Lagnam Spintex Limited",
    "Lakshmi Precision Screws Limited", "Lorenzini Apparels Limited", "Dr. Lal Path Labs Ltd.", "Lambodhara Textiles Limited",
    "Lancor Holdings Limited", "Landmark Cars Limited", "La Opala RG Limited", "Lasa Supergenerics Limited",
    "Latent View Analytics Limited", "Latteys Industries Limited", "Laurus Labs Limited", "Laxmi Cotspin Limited",
    "Laxmi Dental Limited", "Laxmi India Finance Limited", "LCC Infotech Limited", "Le Merite Exports Limited",
    "Lemon Tree Hotels Limited", "Lenskart Solutions Limited", "Lexus Granito (India) Limited", "Lakshmi Finance & Industrial Corporation Limited",
    "LG Balakrishnan & Bros Limited", "LG Electronics India Limited", "Laxmi Goldorna House Limited", "Libas Consumer Products Limited",
    "Liberty Shoes Limited", "LIC Housing Finance Limited", "Life Insurance Corporation Of India", "Likhitha Infrastructure Limited",
    "Linc Limited", "Lincoln Pharmaceuticals Limited", "Linde India Limited", "LLOYDS ENGINEERING WORKS LIMITED",
    "Lloyds Enterprises Limited", "Lloyds Metals And Energ"
  ]
};
